### ISSUE TITLE
art request opc article #3

### ISSUE THREAD

**Issue by Hisma** [flowforge/website#1002]
### Related Issue

https://github.com/flowforge/website/pull/1001

### Description

Just use similar image from previous articles but change the title to match the title of the article - "How to Build an OPC UA Client Dashboard in Node-RED"

and add an "OPC UA part 3" at the bottom right.  
Link to PR - 
https://github.com/flowforge/website/pull/1001

**Comment by Hisma** [comment]
@Yndira-FlowForge

**Comment by Yndira-FlowForge** [comment]
Hi @Hisma here it is!

![Image](https://github.com/flowforge/website/assets/129537638/61060eb3-04b2-4d7d-8f9c-1d612c84d857)
