### ISSUE TITLE
Image for August Webinar

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#1012]
### Description

We need a graphic for the August webinar. Here are the details:

Title: Getting Started with OPC-UA and Node-RED
Speaker: Mika Karaila, Research Director at Valmet Automation
Date: August 30, 17:00CET/11amET

I don't have a picture of Mika so please put something together without a speaker picture. OPC-UA logos can be found at https://opcfoundation.org/developer-tools/marketing-communication-logos/opc-ua-logos/

**Comment by iskerrett** [comment]
@joepavitt I know this is last minute but if you have time today it would be great to be able to publish this webinar today.

**Comment by joepavitt** [comment]
@iskerrett on it

**Comment by joepavitt** [comment]
don't have access to the folder of OPC UA logos, but will try and put something together

**Comment by joepavitt** [comment]
Just double checking date is Wednesday 30th, as I know Webinars are normally on a Thursday?

**Comment by iskerrett** [comment]
> Just double checking date is Wednesday 30th, as I know Webinars are normally on a Thursday?

Yes, the speaker wanted a Wednesday.

**Comment by iskerrett** [comment]
> don't have access to the folder of OPC UA logos, but will try and put something together

Sorry I didn't actually check the link. Kind of dumb of OPC foundation to put their logos behind a paywall. <sigh>

**Comment by joepavitt** [comment]
@iskerrett fyi - also on [Google Drive](https://drive.google.com/open?id=15JikRuO1sHhNf9Ik_Y2aCM1C72L-OZFg&usp=drive_fs)

![1200x630-Webinar-Aug-2023](https://github.com/flowforge/website/assets/99246719/9cad078e-e594-4009-8858-53a7be500bb4)
