### ISSUE TITLE
Why FlowForge #1 - Multi-Instance Applications

### ISSUE THREAD

**Issue by Hisma** [flowforge/website#1016]
### Related Issue

https://github.com/flowforge/website/issues/1015

### Description

link to video - 
https://youtu.be/IdlfMNAJdLM

Per the related issue, @iskerrett wants marketing videos highlighting the benefits of node-red.  
This video addresses #2 on this document - 
https://docs.google.com/document/d/1rrc8y3Iyx7_EA8zOZrYpO_4hlhylwoq00tcdBRfwZ8I/edit

@joepavitt you agreed to jump on this.  I wouldn't really overthink it, just give me something quick I can work with.  I will just go ahead and list the video, but I won't market it yet.  We can just have it hosted on our yt video, and once you can come up with a title picture, I'll go back and add it.

Thanks

**Comment by joepavitt** [comment]
Thanks Richard. I am now done for the day and not back on until Tuesday. @Yndira-FlowForge can probably sort you something on Monday.

**Comment by Hisma** [comment]
works for me, no problem

**Comment by Yndira-FlowForge** [comment]
Hi @Hisma what do you think?
 
![Youtube---How-FlowForge-scales-up-NodeRED](https://github.com/flowforge/website/assets/129537638/1aa75ebf-9326-4bc4-9912-2660d0831ae2)

**Comment by Yndira-FlowForge** [comment]
Here's with the new subtitle

![Image](https://github.com/flowforge/website/assets/129537638/8dee09ee-7c85-4d22-a4ee-61f3b3b633ba)

**Comment by Hisma** [comment]
looks great.  Thanks.  I'll close this and add it to the video.
