### ISSUE TITLE
Graphic for AWS Marketplace announcement

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#1046]
### Description

We will be announcing that FlowFuse is now available on AWS Marketplace. https://aws.amazon.com/marketplace/pp/prodview-3ycrknfg67rug?sr=0-1&ref_=beagle&applicationId=AWSMPContessa

It would be nice to get a graphic for this announcement.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by iskerrett** [comment]
PR is now available #1049

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett wdyt?

![Tile---Blog---FlowFuse-is-now-available-on-AWS-Marketplace](https://github.com/flowforge/website/assets/129537638/7bb747f6-7035-4f7b-a59b-334919609072)

**Comment by iskerrett** [comment]
Love it :-)
