### ISSUE TITLE
Create a partner page

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#1059]
### Description

We should create a partner page so we can link to different partner offering that we have, including:
- Rexroth
- AWS
- Digital Ocean

 I would have the page linked under the company menu.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by iskerrett** [comment]
Thinking about this a bit more. We need to define some partner categories. I think we have the following:
- Referral partners  - what have this page https://flowfuse.com/partners/
- Hosting partners - AWS and Digital Ocean
- PLC Partners - Bosch Rexroth

**Comment by iskerrett** [comment]
Some text for the page.

Title: FlowFuse Partners
Description: FlowFuse partners with leading cloud, hardware, technology and consulting companies to provide a complete solution that allows our customers to deliver results using Node-RED and FlowFuse.


Section 1: 
Title: Cloud Providers
Description: FlowFuse is available for deployment from the marketplace of the following Cloud providers.

Amazon
Digital Ocean


Section 2.
Title: Hardware Partners
Description: FlowFuse partners with key industry hardware partners to provide an integrated experience using Node-RED and FlowFuse.

Bosch Rexroth

Section 3. 
Title: Referral partners
Description: FlowFuse partners with different solution providers to encourage them to recommend and support Node-RED and FlowFuse with their customers.

https://docs.google.com/spreadsheets/d/1y_QDHXt0g9CGvQCsF12zH5nFTmkdfl0rLLRWI85sOMk/edit?usp=sharing

**Comment by iskerrett** [comment]
We should repurpose the existing partner page https://flowfuse.com/partners/ with this new page. The existing page should be moved to https://flowfuse.com/partners/referral-sign-up

**Comment by Yndira-FlowForge** [comment]
HI @iskerrett I've created a mockup with the information you provided in this issue. Should the logos be linked to specific pages? For instance, should the Rexroth logo link to the /ctrlx page?

![Partners](https://github.com/flowforge/website/assets/129537638/1c6ca568-5960-42da-992b-18f8b235b95a)

Under the 'Partners' section, I've added an 'Apply Now' button that will link to the /referral-sign-up page.

Please let me know if this aligns with your vision or if you have a reference for something different.

**Comment by Yndira-FlowForge** [comment]
I looked for references, but most of them seem to emphasize the benefits of being a partner. Do we offer any benefits? Just thinking if we could add more info to this page.

Here are a few references I found (not all are in the same industry as us):
https://www.mendix.com/partners/
https://monday.com/partnership
https://www.wrike.com/partners/

**Comment by iskerrett** [comment]
> I looked for references, but most of them seem to emphasize the benefits of being a partner. Do we offer any benefits? Just thinking if we could add more info to this page.
> 
> Here are a few references I found (not all are in the same industry as us): https://www.mendix.com/partners/ https://monday.com/partnership https://www.wrike.com/partners/

I wouldn't worry about benefits right now. I'd rather do a fast iteration on this page so we can move on to other pages.

**Comment by Yndira-FlowForge** [comment]
> The referral partners should just link to the company home page.

So, should I remove the button that links to the /referral-sign-up page?

**Comment by iskerrett** [comment]
> > The referral partners should just link to the company home page.
> 
> So, should I remove the button that links to the /referral-sign-up page?

No please keep the link to the sign-up page. We want to encourage more referral partners.

**Comment by MarianRaphael** [comment]
> The referral partners should just link to the company home page. @MarianRaphael needs to confirm with each referral partner if they are okay with us hosting their logo.

I'll reach out and check if it's okay for them
