### ISSUE TITLE
Colors on code blocks in docs unreadable

### ISSUE THREAD

**Issue by sammachin** [flowforge/website#106]
### Current Behavior

The current CSS for code blocks in /docs uses dark text on a dark background which makes it unreadable.

For example `/docs/install/local`

![image](https://user-images.githubusercontent.com/187645/167101175-1b387587-6167-4a77-93ad-85aaa6fd0a12.png)

### Expected Behavior

Need contrast between text and background, will need all the different styles to be reviewed as some has a light text already so just changing the background to light doesn't fix.

### Steps To Reproduce

goto https://flowforge.com/docs/install/local

### Environment

N/A

**Comment by sammachin** [comment]
It didn't work locally for me, wonder if its related to the script that imports the docs from the other repo,

**Comment by joepavitt** [comment]
hmmm... or a package version difference somewhere?

**Comment by ZJvandeWeg** [comment]
Has been fixed by: https://github.com/flowforge/website/pull/114
