### ISSUE TITLE
Graphic for Why FlowFuse page

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#1071]
### Description

We need a graphic for the Why FlowFuse page so when we link to the page on social media we don't get the default FlowFuse - DevOps for Node-RED image.

I would suggest the image has somthing like:
Why FlowFuse? What FlowFuse adds to standard Node-RED.

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett 

Here's a version with only text
V1
![og-why-flowfuse](https://github.com/flowforge/website/assets/129537638/05a45a97-f826-493c-9038-f3b8360987ba)

And here's an alternative with a pseudo screenshot of the platform
V2
![og-why-flowfuse_1](https://github.com/flowforge/website/assets/129537638/3d51c858-1a9d-4bea-9b9e-aa74b0e70155)

**Comment by iskerrett** [comment]
I like the second one. Can you add it to the page?
