### ISSUE TITLE
Update homepage

### ISSUE THREAD

**Issue by Yndira-FlowForge** [flowforge/website#1086]
### Description

Update the homepage to be more like the /why-flowfuse page

**Comment by Yndira-FlowForge** [comment]
Hi @ZJvandeWeg @iskerrett I opened this issue to discuss the homepage update here.
Here's a quick mockup, with the same content we have in the why FlowFuse page. I can start working on updating the code while Ian updates the content and create the new video.
![Homepage - V2 0](https://github.com/flowforge/website/assets/129537638/ab137edf-2c41-4d11-af12-c5b2fad43e0d)

**Comment by ZJvandeWeg** [comment]
Compliance is about what Node-RED versions one is running, understanding which custom nodes are installed, tracing what changes in that regard where made. Furthermore, no more sharing passwords and because they now don't full audit logging is available. Which again helps with remaining compliant on the customers' side.

Collaboration features is more around effectively working together. Sharing knowledge etc

**Comment by iskerrett** [comment]
I think there is some overlap with the team video I prepared. When I spoke to Nick about the 6 reasons he pointed out that the real advantage of FlowFuse for team was you can do it securely with audit logs. Here is the script for video #4. https://docs.google.com/document/d/1WZrOC2rxOauQFaocjYLI06sJuB23EbFxXMfajTjVV3w/edit?usp=sharing

I think it is fine to having overlap but I just want to point it out.

How do you see custom nodes in FlowFuse? I am not sure how to demo that.  For tracing changes, is this the audit log for an instance or are you thinking of something else?

For real compliance, I think SOC2 certification will be a key point too.

**Comment by ZJvandeWeg** [comment]
@iskerrett I like the script, and while there's some overlap with compliance, I don't think it's a lot. Though almost all compliance requirements include a line about not sharing usernames and passwords, which is something the Node-RED community should leave behind. Agree that this minor overlap should be fine.

I think custom nodes in the messaging would be selling roadmap items, next release onwards FlowFuse allows you make a subset of nodes available for your developers. Not all. That's a huge benefit to not run untrusted code.

**Comment by ZJvandeWeg** [comment]
@Yndira-FlowForge Can we move the social proof logos to right under the video and make the page more dense? The Flow feels off this way.

Additionally I wonder if "Why FlowFuse" should be more like Confluent; Achieve Node-REDs full potential with FlowFuse. WDYT?

**Comment by Yndira-FlowForge** [comment]
> I'd be fine with shipping this screenshot as first iteration, and keep iterating over the next weeks. Is that possible?

Yes! I just push that change, should I remove the `/why-flowfuse` page?

**Comment by ZJvandeWeg** [comment]
I think so, yes.

**Comment by Yndira-FlowForge** [comment]
> Can we move the social proof logos to right under the video and make the page more dense? The Flow feels off this way.

This has been done. I agree with you about the flow of the page. I considered this when I initially added the logos, but I thought that it might result in fewer users clicking the "What is Node-RED" link, and at the time, that seemed more important than the social proof.

> Additionally I wonder if "Why FlowFuse" should be more like Confluent; Achieve Node-REDs full potential with FlowFuse. WDYT?

Perhaps, instead of replacing the "Why FlowFuse" text, we could add that text before Nick's video? All the other video scripts start with "reason number XX," like the answer to the "why FlowFuse" question. We could also edit all the videos, remove that phrase, change the intro graphics, and remove the numbers next to the titles, but that could be part of the next iteration... What do you think? @ZJvandeWeg @iskerrett
