### ISSUE TITLE
Graphic for Rexroth ctrlX offering

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#1087]
### Description

We are announcing our partnership with Rexroth and our offering in their ctrX World marketplace. We will need a graphic for this annoucnement.

Here is the draft post.  https://docs.google.com/document/d/1xXLSQmthxAoL2RUKPdEccptaE7C1RQlwDLr57YCsWIA/edit?usp=sharing

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett 

How about this one?

![Image](https://github.com/flowforge/website/assets/129537638/0e4ded7b-3139-47e9-9d47-88f013f642a3)

**Comment by iskerrett** [comment]
Here is the PR #1101
