### ISSUE TITLE
Graphic for new NR case study featuring UN Weather agency

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#1094]
### Description

We have a new Node-RED case study that features the UN World Meteorological Organization. We will need graphics to be created for the case study.

Here is the text  https://docs.google.com/document/d/1NopBaAiNphOTMyMmwSn-cbU1Zjw1XPdLEvwN9JaYGf0/edit?usp=sharing

**Comment by iskerrett** [comment]
See PR #1095

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett 

![Image](https://github.com/flowforge/website/assets/129537638/ee75a0ff-0d3c-4e71-98e4-415effa88e9c)


![Image](https://github.com/flowforge/website/assets/129537638/a186937f-4f0b-4752-afb7-6f805de30ea6)

Let me know if it's ok and I'll push the changes to your branch.

**Comment by iskerrett** [comment]
It looks good.
