### ISSUE TITLE
Graphic for September webinar

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#1104]
### Description

Title: Celebrate 10 Years of Node-RED and What’s New in 3.1 and Beyond

Date: September 21 @ 17:00CET/11:00AM ET
Speaker: Nick O'Leary

Here is a link to the abstract. https://docs.google.com/document/d/1M_usSUoTGQGgC_HIfh_Sx9X1rj1WPT9fV3KGCowYntQ/edit?usp=sharing

**Comment by iskerrett** [comment]
Here is the PR #1105

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett I just added it to the PR

![Image](https://github.com/flowforge/website/assets/129537638/c2ab2bbc-ea5f-4c02-a3c5-791c8677a59c)

**Comment by Yndira-FlowForge** [comment]
@iskerrett the date on the image was wrong (my bad, sorry). I updated it on the web before leaving for vacations, I just wanted to update it here too in case you need it for something else.


![Image](https://github.com/flowforge/website/assets/129537638/5a0e06fc-2739-46c4-a979-49cb6c4b4a20)
