### ISSUE TITLE
Graphic for blog post about industrial data parsing

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/website#1109]
### Description

**Considerations:**
- This image is for a blog post
- It will potentially be the first of several related posts centred on "Making sense of your industrial data"

**Inspirations:**
- Something that illustrates messy, unsorted, raw industrial data (ModBus, Siemens, Omron, Mitsubishi, Allen Bradley) being nicely formatted into sensible values
- On the left, legacy / old / dated
- On the right, Modern / new / IoT / IIoT
- Something like industrial protocol data going through cogs ending up in nice data e.g: something like [this](https://www.stupidproxy.com/wp-content/uploads/2020/06/Data-Parsing-meaning.jpg) or [this](https://global-uploads.webflow.com/64be86eaa29fa71f24b00685/64be86eaa29fa71f24b00fc1_60ed7c215285777cea2755c6_Introduction%252520to%252520Data%252520Parsing%252520Main%252520image-p-1600.jpeg) 
   - On the left, a selection of inputs that signify raw data / 16 bit data / un-parsed data
   - On the right, a selection of output including MQTT, {JSON}, INFLUX, A GRAPH

**Comment by Yndira-FlowForge** [comment]
Hi @Steve-Mcl how about this one?


![Image](https://github.com/flowforge/website/assets/129537638/ec992c10-75fa-4d38-ab85-6f294678082a)

**Comment by Steve-Mcl** [comment]
Oooh, it's so pretty. Thank you Yndira.
