### ISSUE TITLE
Update home page

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#1129]
### Description

We need to update our home page to reflect new messaging. This issue will track the iterative changes we need to make.

Proceed with the messaging at the bottom of this document.  https://docs.google.com/document/d/1ah7GwOXOTF0AMYB1KzNLh0kQnQI8ZSNq87ytNtb02MQ/edit?usp=sharing

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
@Yndira-FlowForge @iskerrett Can we write what step two is? It would be great to iterate tomorrow

**Comment by Yndira-FlowForge** [comment]
Hi @ZJvandeWeg the plan would be:

- Remove the why FlowFuse list.
- Create a separate page for it, like we had before.
- Work on a mockup including the messaging at the bottom of [this document](https://docs.google.com/document/d/1ah7GwOXOTF0AMYB1KzNLh0kQnQI8ZSNq87ytNtb02MQ/edit?usp=sharing). I'm gonna have to create some graphics to go with the text.
- When we agree on the design, implement and publish.

I'm working on the mockup and graphics, I will add the updates to this issue.

**Comment by Yndira-FlowForge** [comment]
I decided to use some pictograms that I think fit the concepts we're explaining, this could be a first iteration:

Here's a [**simple prototype**](https://www.figma.com/proto/hXDN5PnY3TmeQSv3n7Hna5/FlowForge-Website?page-id=0%3A1&type=design&node-id=2829-19291&viewport=-14044%2C-4378%2C0.5&t=N1Dg10fWrdQ0WInT-1&scaling=min-zoom&starting-point-node-id=804%3A2591&show-proto-sidebar=1&mode=design)

![Homepage - V3 0](https://github.com/flowforge/website/assets/129537638/c34c26c9-bf2b-4941-a0b1-e9ebddbd984a)

I can create new, more complex graphics for the next iteration.

**Comment by iskerrett** [comment]
A great first iteration. Some feedback:
- the title should be 'Accelerate Digital Transformation with FlowFuse and Node-RED'
- the subtitle 'Why FlowFuse for Node-RED' might be better to read 'Why FlowFuse with Node-RED'
- I don't think we need the numbers on each section.
- It feels like there is too much white space between each section.
- I think the 'teams of citizen developers' should be the red text for that bullet and 'manage and configure' should be red for that bullet.

Looks very promising. :-)

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett thanks for the feedback 😃 

> the title should be 'Accelerate Digital Transformation with FlowFuse and Node-RED'
> the subtitle 'Why FlowFuse for Node-RED' might be better to read 'Why FlowFuse with Node-RED'

I'll update those in the code, all I have now is a screenshot.

The rest is updated now in [the prototype](https://www.figma.com/proto/hXDN5PnY3TmeQSv3n7Hna5/FlowForge-Website?page-id=0%3A1&type=design&node-id=2829-19291&viewport=-14044%2C-4378%2C0.5&t=N1Dg10fWrdQ0WInT-1&scaling=min-zoom&starting-point-node-id=804%3A2591&show-proto-sidebar=1&mode=design) and here:

![Homepage - V3 0](https://github.com/flowforge/website/assets/129537638/2c4f7492-534c-47d2-83f2-c4285fa7bc6e)
