### ISSUE TITLE
ChatGPT improving dev experience 

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#1136]
### Description

**Considerations:**
- Blog tile

**Inspirations:**
- chatgpt function node tile
- Developer happiness and experience

**Comment by Yndira-FlowForge** [comment]
Hi @ZJvandeWeg how about this one?
![ChatGPT-improving-dev-experience](https://github.com/flowforge/website/assets/129537638/1471507b-24f1-4e78-a34a-03432c53cda1)

**Comment by ZJvandeWeg** [comment]
😻
