### ISSUE TITLE
Blog post image request: technical rebranding

### ISSUE THREAD

**Issue by knolleary** [flowforge/website#1166]
### Description

Currently writing a blog post about the next step in the rebranding - specifically about the renaming of our technical assets (github/npm/docker etc).

This is a lower-level technical rebranding - changing the names of our packages and containers. Something a bit fun like a cardboard box with the old name crossed out and the new name written in place?

**Comment by Yndira-FlowForge** [comment]
Hi @knolleary is something like this what you had in mind?


![Image](https://github.com/flowforge/website/assets/129537638/393f6090-bcb8-42ba-b153-99a2a76fa9c8)
