### ISSUE TITLE
Add "Hosted in Ireland" to the product page for FF Cloud

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#119]
### Description

Right now there's no advertisement of where FlowForge is hosted. It being hosted in Europe a something we should list as a feature.

**Comment by ZJvandeWeg** [comment]
@joepavitt I broke the table on the page trying to implement this in a quick and dirty way. Do you know how to elegantly pick this up?

**Comment by joepavitt** [comment]
Without seeing what code changes you've made, it's difficult to know what you did wrong - do you have a branch I can look at?
