### ISSUE TITLE
Broken template: object doesn't respond to replace() 

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#128]
### Current Behavior

```
`TemplateWriterWriteError` was thrown
> (./src/_includes/layouts/handbook.njk)
  TypeError: Cannot read properties of undefined (reading 'replace')
```

### Expected Behavior

I can just run `npm run dev:eleventy`

### Environment

- Node.js version: ?
- npm version: ?
- Platform/OS: Apple M1
- Browser: Chrome

**Comment by joepavitt** [comment]
Delete the contents of `website/src/handbook` (except for `handbook.json`).

I had this issue this morning, and @knolleary pointed to me to the fix. Eleventy isn't great at clearing out old built files that aren't used anymore.
