### ISSUE TITLE
Callout Valuable Integrations

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#130]
### Description

As part of the landing page, we should be calling out recognisable integrations we offer (e.g. twitter, mqtt) that customers will relate to. Currently, our homepage is very vague.

Design to come, but my thinking at the moment is that we show 4+ high level groups of integrations we offer (e.g. socials, hardware), then beneath the icons/pictogram for each group, we list a few of the most recognisable ones.

This will replace the existing 0.1 intro video, and later, the Landing Video will also be included on the homepage.

Currently, in our [draft landing video](https://github.com/flowforge/website/issues/78#issuecomment-1149818673), we have the following integrations advertised:

- **Socials**: Facebook, Twitter, Telegram, Slack, WhatsApp, Discord
- **Cloud Services**: AWS, Azure, S3
- **AI & Smart Home**: Alexa, Azure Cognitive Services, Google Home, IBM Watson, TensorFlow
- **Storage**: MongoDB, MySQL, Redis, DB2, MSSQL, CouchDB, DashDB, CloudantDB
- **Media**: Storage Tools, OpenCV, SVG, FFMPEG
- **File Support**: CSV, Json, XML, YML, ONVIF
- **Hardware**: Arduino, Raspberry Pi
- **???**: Websockets, HTTP, MQTT, RSS, E-Mail, FTP, SNMP

Note sure where these group:
- OPCUA, S7, MC Protocol, FINS Protocol, OpenProtocol, ZWave, Zigbee, Twilio, Viseo, AMQP, SSH

**Comment by joepavitt** [comment]
@Steve-Mcl can you run through these and group them into something sensible please that would appeal to our customers/stakeholders?

**Comment by Steve-Mcl** [comment]
- Social: Twitter, Twillo, Telegram, Slack, WhatsApp, Discord, Facebook
- Cloud: AWS, Azure, S3
- Smart: Alexa, Azure Cognitive Services, Alexa, Google Home, IBM Watson, TensorFlow, ZWave, Zigbee
- Storage: MongoDB, MySQL, PostgreSQL, SQL Server, Redis, DB2, CouchDB, DashDB, CloudantDB
- Media: OpenCV, SVG, FFMPEG, Image Processing
- ~~File Support: CSV, Json, XML, YML, ONVIF~~ move to storage?
- Hardware: Arduino, Raspberry Pi, Zigbee
- Industrial Protocols: OPCUA, ModBus, Siemens S7, Mitsubishi MC Protocol, OMRON FINS Protocol, OpenProtocol
- Communication: WebSocket, HTTP, MQTT, AMQP, SNMP, RSS, E-Mail, FTP

Other potential categories to consider...
* Digital transformation - this could encompass a lot of the social/protocol/communication stuff
* Field - could encompass industrial protocols and hardware


NOTE: I have added and removed a hand full of items under several headers (and slight juggling too)

Hope that helps - let me know if you need something different.

**Comment by joepavitt** [comment]
Draft pass on how these will be laid out:
<img width="1322" alt="Screenshot 2022-06-08 at 15 13 19" src="https://user-images.githubusercontent.com/99246719/172638825-b9fbe068-89f3-484a-ace5-0ce810830e85.png">

**Comment by Steve-Mcl** [comment]
What will be in the boxes Joe? 

Where / how do you see the text displayed - as it is now in a CSV list?

**Comment by joepavitt** [comment]
> Smart: Alexa, Azure Cognitive Services, Alexa, Google Home, IBM Watson, TensorFlow, ZWave, Zigbee

Can we think of an alternative term, instead of "Smart". I see what you're doing in grouping AI/Smart Home & Home IoT stuff together, but "Smart Home" and "AI" may not warrant their own groups? Arguably "Smart Home" could warrant it's own group actually...

**Comment by joepavitt** [comment]
> What will be in the boxes Joe?

Placeholders for pictograms/icons that will match the style of the rest of the website. Just left them blank for now as to not get bogged down in iconography discussion/opinions

**Comment by ZJvandeWeg** [comment]
I like the iteration on the homepage. I wonder though if we should invest in a onboarding guide? To answer "how" you integrate them.

**Comment by joepavitt** [comment]
> I like the iteration on the homepage. I wonder though if we should invest in a onboarding guide? To answer "how" you integrate them.

Would that not partly be responsibility to (to be hired) developer advocate/educator/content creator

**Comment by Steve-Mcl** [comment]
TBH, Twillo & Telegram can be part of messaging too.  Not 100% certain categories are best fit. 

An endless (mixed) list underneath the set of icons may be a better fit? Perhaps the text could be coded e.g. Database stuff in a different colour/format to AI etc?

**Comment by ZJvandeWeg** [comment]
> Would that not partly be responsibility to (to be hired) developer advocate/educator/content creator

@joepavitt yes, but now it's everybody's responsibility. So we should start iterating

**Comment by joepavitt** [comment]
First pass (with icons):

<img width="938" alt="Screenshot 2022-06-08 at 17 54 44" src="https://user-images.githubusercontent.com/99246719/172673505-2c8fa382-55f6-4a3f-8571-51a4382e004a.png">

**Comment by sammachin** [comment]
Personally the word `Messaging` doesn't make me think of those things which are protocols,

I would also change Socials to Communications

**Comment by joepavitt** [comment]
@sammachin any better?

<img width="912" alt="Screenshot 2022-06-09 at 11 27 31" src="https://user-images.githubusercontent.com/99246719/172826379-40143264-bebe-4bf3-b026-42bd0f605070.png">

**Comment by joepavitt** [comment]
Closed by #132
