### ISSUE TITLE
Link issue in Footer (Website)

### ISSUE THREAD

**Issue by nerdjfpb** [flowforge/website#140]
### Current Behavior

Handbook link is going down after clicking!

https://user-images.githubusercontent.com/47062625/174080917-abdbb94b-8ccb-4702-97c7-d6a8e8b37bf1.MOV

### Expected Behavior

Should stay in same line (My opinion). But I can be wrong.

### Steps To Reproduce

1. Go to website from mobile or mobile view
2. Click on the handbook link

### Environment

- Platform/OS: iOS 15.5
- Browser: Safari

**Comment by joepavitt** [comment]
Thanks for raising this @nerdjfpb - will get on the case to fix it.

**Comment by joepavitt** [comment]
@nerdjfpb Which iPhone are you using for this? Struggling to find the resolution/sizing that triggers this issue.

**Comment by nerdjfpb** [comment]
I am using iphone 13 pro max @joepavitt
