### ISSUE TITLE
Solution pages

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#161]
### Description

FlowForge doesn't have concrete copy on what problem we're solving exactly for our customers. Right now our marketing is focussed very broadly on Node-RED in general.

Our corporate website should have dedicated pages for the different solutions FlowForge provides today.

**Comment by joepavitt** [comment]
Not a full page, but I really like this on n8n's home page:

<img width="1604" alt="Screenshot 2022-10-16 at 13 49 18" src="https://user-images.githubusercontent.com/99246719/196048360-d256dc95-d077-49b2-9221-f207ff7ad172.png">
