### ISSUE TITLE
Front page ~inaccurate~ too modest - there are now over 4000 contributions

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/website#170]
### Current Behavior

![image](https://user-images.githubusercontent.com/44235289/187939335-771af9b6-9e46-4abd-9ef2-15994371d4b3.png)

### Expected Behavior

Should be updated to reflect there are now over 4000 contributions

![image](https://user-images.githubusercontent.com/44235289/187939617-70d2d751-ea1e-4369-9709-4e8d1e57604c.png)

### Steps To Reproduce

visit homepage https://flowforge.com/

### Environment

- FlowForge version: 0.9.0

**Comment by knolleary** [comment]
https://github.com/flowforge/website/pull/168 already has the change to update the number.
