### ISSUE TITLE
Rebrand 'Cloud' to SaaS

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#175]
### Description

Customers might host FlowForge in the cloud too, as such the branding of "Cloud" doesn't specify a different edition or tier. Rebranding should remove "Cloud" working in favour of SaaS.

### Acceptance Criteria

- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3
- ...

**Comment by ZJvandeWeg** [comment]
@knolleary Did you volunteer to pick this up?

**Comment by knolleary** [comment]
Yup - will get a first iteration PR in place
