### ISSUE TITLE
Release: 1.0 release video

### ISSUE THREAD

**Issue by knolleary** [flowforge/website#182]
### Description

 - Capture key highlights and content for the 1.0 release video

**Comment by joepavitt** [comment]
Working with @robmarcer on this one

**Comment by knolleary** [comment]
So does that mean we're aiming for *three* videos this week?

 - 1.0 release video
 - What is FlowForge
 - Quick intro to flowforge #202

**Comment by joepavitt** [comment]
I believe so - the "What is FlowForge" will mostly be an update of https://www.youtube.com/watch?v=BBNzFInc_2E I think, unless I'm mis-understanding what we need?

**Comment by robmarcer** [comment]
Features to cover in the video.

[Add well-defined env vars to launcher/device environments#841](https://github.com/flowforge/flowforge/issues/841)

[Preinstall Palette Nodes#405](https://github.com/flowforge/flowforge/issues/405)

[Import Credentials#835](https://github.com/flowforge/flowforge/issues/835)

**Comment by knolleary** [comment]
Release video updated via https://github.com/flowforge/website/pull/225
