### ISSUE TITLE
Clearer overall Handbook navigation 

### ISSUE THREAD

**Issue by Pezmc** [flowforge/website#193]
#### As a:

Team Member / interested third party

#### I want to:

- See an overview of all the pages in the handbook
- Be able to browse the whole handbook in an easy order

#### So that:

- I can quickly find the information that's relevant to me
- I know what is and isn't in the handbook at a glance

----

Noticed when going through the handbook for the first time, I ended up navigating the markdown files on disk instead of on the website since the hierarchy isn't particularly clear right now (the manual table of contents + on this page sections).

**Comment by ZJvandeWeg** [comment]
@Pezmc Do you want a user friendly sitemap: https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview?

**Comment by Pezmc** [comment]
I don't think something fully automated fills this gap; but something halfway between a true sitemap and the current table of contents would probably work (as well as making the "on this page" section less confusing).

**Comment by joepavitt** [comment]
Agree with this - the biggest confusion with the handbook imo is the "On This Page" widget often reads like a Table of Contents, but actually, the ToC is often embedded in the page.

**Comment by joepavitt** [comment]
Not going to get done in 1.2, shifting to 1.3

**Comment by robmarcer** [comment]
Just to throw in an idea, a search tool would be very useful.

I'm often trying to find something in the handbook which I know will contain a specific term but I can't navigate my way to it. As @Pezmc said I often just pull main to my laptop then use my file explorer to search the content.

Being able to search for a string would give me confidence that I'd either read the relevant part of the handbook or that there isn't anything covering that topic.

**Comment by joepavitt** [comment]
> Just to throw in an idea, a search tool would be very useful.

Agree - I've found [PostHog's handbook](https://posthog.com/handbook) and it's really easy to navigate (and search). Have asked in their Slack what they use.

**Comment by joepavitt** [comment]
@ZJvandeWeg interesting take from PostHog re: our upcoming hires - "Everyone Codes": https://posthog.com/blog/a-non-coders-thoughts-on-everybody-codes-culture

<img width="408" alt="Screenshot 2022-12-22 at 11 40 17" src="https://user-images.githubusercontent.com/99246719/209126799-57cd0f01-5018-47e0-a961-14b94b15064d.png">

**Comment by joepavitt** [comment]
<img width="1769" alt="Screenshot 2022-12-23 at 10 37 55" src="https://user-images.githubusercontent.com/99246719/209321542-69e0d748-9d64-494b-9f1a-750add08825f.png">

**Comment by joepavitt** [comment]
part two of PostHog's onboarding/everyone should code: https://posthog.com/blog/a-non-coders-thoughts-on-everybody-codes-culture-part-two

**Comment by joepavitt** [comment]
More insight from PostHog: 

<img width="848" alt="Screenshot 2022-12-23 at 15 01 07" src="https://user-images.githubusercontent.com/99246719/209356544-97fe9fc0-9936-4275-b71d-5c82f056c8ef.png">

**Comment by joepavitt** [comment]
Progress made today - have auto-generated side navigation created. Optional "titles" can be given to all pages in the Handbook `md` file too.

<img width="1713" alt="Screenshot 2023-01-04 at 17 33 56" src="https://user-images.githubusercontent.com/99246719/210615310-4ac4553f-49a2-4888-82a7-5de2e3f9bc04.png">

Need to work on:
- consistent ordering
- styling
- expanding/minimising navigation options

May also introduce the concept of `navGroup` for the top level folders which may offer better grouping, still TBD
