### ISSUE TITLE
Clearer CTAs on Homepage

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#199]
### Description

Currently, we have the following CTAs:

<img width="1076" alt="Screenshot 2022-10-16 at 17 44 56" src="https://user-images.githubusercontent.com/99246719/196047581-81bda264-c4e1-410f-aea2-eb3a56942eb2.png">

at the point of first arrival, new customers/visitors are unlikely to have knowledge of our different offerings, as such "Sign Up" and "Install" are vague and confusing - do I need to sign up in order to install? 

We should have clearer distinction between these actions, as such I propose the following:

<img width="1909" alt="Screenshot 2022-10-16 at 17 46 11" src="https://user-images.githubusercontent.com/99246719/196047629-4999013a-40c6-41d3-8c17-6bc95240c459.png">

Where the "FlowForge Cloud" is, I know, going to open a can of worms in itself, but let's restrain this issue to the clearer messaging component.

_note: the design changes here also include/assume merging of https://github.com/flowforge/website/pull/200_

**Comment by knolleary** [comment]
> Where the "FlowForge Cloud" is, I know, going to open a can of worms in itself, but let's restrain this issue to the clearer messaging component.

If you want to avoid a can of worms, then don't use the term we've just done the work to remove from the site :)

If you want a quick iteration, then copy the wording from the Product page's CTA:

<img width="362" alt="image" src="https://user-images.githubusercontent.com/51083/196131222-ca971b95-6af6-487a-adde-559f7befa7e2.png">
