### ISSUE TITLE
Render team page on our website

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#20]
While the team data is captured in this repository, it's not rendered on the website. I propose a team page with details about the team, and who's joined FlowForge.

**Comment by joepavitt** [comment]
Will we want any form of headshots for each team member here? We have the socials, job title and name, can also do "Employee Number" maybe?

**Comment by joepavitt** [comment]
It's linked to via a `Team` option in the `Company` footer at the moment:

<img width="151" alt="Screenshot 2022-02-09 at 12 54 45" src="https://user-images.githubusercontent.com/99246719/153205290-28bdfb4c-264f-4ea7-9899-534b8cf605ff.png">

**Comment by joepavitt** [comment]
If no particular feedback/requests for changes, then I'll open up a PR. I was toying with the idea of using @knolleary's gen code to have little avatar type flow art bits, but thought it'd get too busy for busy-sake. 

Headshots would improve the general visual style imo, but appreciate that everyone may not want to do that.

**Comment by sammachin** [comment]
My job title changed to 'Community Product Manager' end of last year

**Comment by joepavitt** [comment]
Open to preferences/opinions on left/center align on the mobile view btw. With headshots in, definitely left-align as the headshot would sit nicely to the left of the content. Without, I think the content looks better center aligned, but not without the page header also being center aligned (which isn't a change I'm comfortable making as it'll effect every other page)

<img width="416" alt="Screenshot 2022-02-09 at 13 38 51" src="https://user-images.githubusercontent.com/99246719/153212532-3d26075e-fe71-4fca-a4d4-0052ed578391.png">

<img width="415" alt="Screenshot 2022-02-09 at 13 39 40" src="https://user-images.githubusercontent.com/99246719/153212603-55fe1010-19de-48fd-84bd-132e98a36ceb.png">
