### ISSUE TITLE
Custom Posthog Events for Primary CTAs

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#208]
### Description

Posthog enables analysis of user paths. Whilst we have a good understanding of users > CTA through posthog funnels, this requires us to make pre-defined/expected journeys - it's normally used for something like racking a user through a purchase journey.

Given our CTAs are more flexible, and appear at various points across our application, it would be beneficial to be able to filter and analyse with the "End Event" being our CTA. Whilst we can define "Actions" in Posthog, to record button clicks, PH currently prevents these actions from being embedded in "User Path" and "Funnel" analysis. As such, we need to emit our own custom events on button click.

We currently inject Posthog into our website via https://github.com/flowforge/website/blob/main/src/_includes/layouts/base.njk 

Posthog makes the custom events API available via https://posthog.com/manual/actions#custom-events

GIven our need for custom events, we would need to look at using one of their client libraries to achieve this.

**Comment by joepavitt** [comment]
@hardillb do we have any hard/guaranteed steps in the domain of flowforge.com that we can monitor _after_ they've arrived at the `/install/...` page for local/docket/k8s?

**Comment by knolleary** [comment]
Following the work in 1.1 to improve the install docs for Local, I believe the 'expected' journey is:

 1. Get to https://flowforge.com/docs/install/local/
 2. (they may choose to look at https://flowforge.com/docs/install/configuration , but that is optional in the text)
 3. Go to https://flowforge.com/docs/install/first-run/
 4. If they get to the end of 'first-run', they are directed to https://flowforge.com/docs/user/

**Comment by joepavitt** [comment]
verified we now get the `cta-*` events in PostHog
