### ISSUE TITLE
Redesign Pricing Page

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#209]
### Epic

#203

### Description

**As a:** prospective customer of FlowForge

**I want to:** get a clear understanding of my options and costs associated to the platform

**So that:** I can make an informed decision as to whether FF is for me, and if so, which hosting/deployment option best suits my needs

Original Design:

<img width="1664" alt="Screenshot 2022-10-20 at 13 08 09" src="https://user-images.githubusercontent.com/99246719/196944347-985df7f1-4226-4471-bdf3-29eb116082e3.png">

Adapted with new "Premium" terminology:

<img width="1267" alt="Screenshot 2022-10-20 at 13 07 12" src="https://user-images.githubusercontent.com/99246719/196944230-80c27c42-1963-4cc4-991f-744bfce306e1.png">

### Acceptance Criteria

- [ ] New Design
- [ ] Dev Work

**Comment by knolleary** [comment]
Works for me

**Comment by joepavitt** [comment]
@knolleary We make explicit mention on this page of features being "On the Roadmap" - which version of our roadmap am I best linking to here?

**Comment by knolleary** [comment]
We have the roadmap project board. However I'm not sure how well it works as a standalone thing for someone to browse without any context currently. For example, it doesn't include the items we know we want to get to eventually, but don't have planned in the next 1-3 releases. It is also getting a bit unwieldy as it has the historical releases - and all the current/future stuff is now scrolled off to the right. Pointing them at the raw issue list isn't helpful either.

For the right now, I'd say don't link to anything yet. I will do some research around how other companies/projects communicate their roadmaps. We can discuss on Tuesday.

**Comment by ZJvandeWeg** [comment]
@knolleary @joepavitt 

> For the right now, I'd say don't link to anything yet. I will do some research around how other companies/projects communicate their roadmaps. We can discuss on Tuesday.

We can keep it high level, with our 1 year goals based on the 4 pillars. That prevents churn on this page too. 

1. Enterprise: Most secure and compliant way to run
2. Devices: Deploying to and maintaining your flows where ever they're deployed (attaching a remote NR, sending errors etc back to FF, etc etc)
3. Best place to run NR: Invest in dash boarding that's multi-tenant with the community, Node-RED LTS, Currated custom nodes directory?
4. Collaboration: Allow teams of tens developers to work on one project (So no tab locking etc)

What do you think of setting goals in such a way, over concrete items?

**Comment by ZJvandeWeg** [comment]
> @ZJvandeWeg @knolleary thoughts very welcome on the above before I commit to any dev work please

The proposal is great! :shipit:

**Comment by joepavitt** [comment]
Desktop:

https://user-images.githubusercontent.com/99246719/197178596-8eff4f6c-e5da-40ac-9ee7-758d412e3ea2.mov

Mobile:


https://user-images.githubusercontent.com/99246719/197178790-7b13e897-6494-4d05-b939-ddc051c943f1.mov

**Comment by joepavitt** [comment]
Closed by https://github.com/flowforge/website/pull/211
