### ISSUE TITLE
Identical heading styling for different headings

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#214]
### Current Behavior

`/docs/install/local` age has nested headings in the "Mosquitto" section that look like new sections, but are in fact children elements.

Here, `Mosquitto` is a parent heading of `Manual`

<img width="724" alt="Screenshot 2022-10-14 at 11 08 32" src="https://user-images.githubusercontent.com/99246719/195821659-89ec00e2-0b38-4ffd-9084-4e6592e6b930.png">

### Expected Behavior

CSS should differentiate between H3/H4/H5

### Steps To Reproduce

Navigate to https://flowforge.com/docs/install/local/#mosquitto

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by joepavitt** [comment]
Issue caused by the Tailwind `prose` only providing default styling for `h1` > `h4`. Will redefine styles for our headings to prevent a requirement to restructure docs.

**Comment by Pezmc** [comment]
Verified on prod (though not tied to release)
