### ISSUE TITLE
Ability to add custom images to blog post headers where we have something suitable

### ISSUE THREAD

**Issue by robmarcer** [flowforge/website#236]
### Acceptance Criteria

- [ ] Have a way to set the image path.
- [ ] Where that is not set revert to an image generated by the existing code.
- [ ] Have a way to go back to add images to pre-existing blog posts.

Notes - To be clear I am referring to these images - https://d.pr/i/3LuAu2

**Comment by ZJvandeWeg** [comment]
@robmarcer can this issue be closed?

**Comment by joepavitt** [comment]
Believe this issue can now be closed?

**Comment by knolleary** [comment]
Yes definitely.
