### ISSUE TITLE
The unsub link on the Buttondown newsletters does not work

### ISSUE THREAD

**Issue by robmarcer** [flowforge/website#237]
### Current Behavior

When I click the link to unsub it should allow me to opt out of the mailing list.

### Expected Behavior

It takes me to the homepage.

### Steps To Reproduce

Follow an unsub link on the footer of the newsletter.

http://email.flowforge.com/c/eJyNjkuKxDAMRE8T7xxsWf5k4UVv5hqNbMvTgXwaJ6GvPyab2TaIQiWq0OOonfM2aAValMjkMwYxR1AAWivUznqlxwKTArbGo5-8rWFAVZf9U_f2y2PeV_GKlpUJPkMgVM4nzBPZSXsmtCYgWLHE13m-j8E8Bvjpk67z3Leyf7aRV5qXfqL33PV2R1-u7bjSkducuDtg52tJIEM2XmJmkiF4ko4Q-6usFBXRYttTp1upZW432hnR1WzATJKDzhJrQElkUYIjkywxV67iH-d5Azzn8l3xTn8V_QPlwGuf

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by robmarcer** [comment]
I suspect this is a DNS issue for the domain email.flowforge.com. I'm working on getting to the bottom of it.

**Comment by robmarcer** [comment]
It does look to be unsubscribing people who follow the link but it's not confirming to them that was done.

**Comment by robmarcer** [comment]
I've raised this with the provider of our email list, I don't think the problem is on our side.

**Comment by ZJvandeWeg** [comment]
@robmarcer Any feedback on this issue? Or should we just move away from buttondown? They keep having issues.

**Comment by robmarcer** [comment]
We are stopping using Buttondown so this no longer needs to be resolved.

**Comment by hardillb** [comment]
Can I move this to the done column? Have we sent our last buttondown email?

**Comment by robmarcer** [comment]
Yes it can be moved to done and yes we've sent our last email. That link is to the kanban, which issue were you referring to?
