### ISSUE TITLE
"Features" Page

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#254]
### Description

- [x] https://github.com/flowforge/website/pull/271
- [ ] https://github.com/flowforge/website/pull/273
- [ ] https://github.com/flowforge/website/issues/292
- [ ] https://github.com/flowforge/website/issues/194

Inspiration:
- https://confluent.io

**Comment by joepavitt** [comment]
I like the krysp approach of having a "Features" page, rather than "Product": https://www.krysp.io/features

"Product(s)" is suitable if we have more than one, but we seemed set on saying we have _one_ product - FlowForge, not a breakdown of FlowForge Cloud/Comminity, etc.

**Comment by joepavitt** [comment]
@ZJvandeWeg based on the conversations you've been having, could you drop 5-10 FAQs here please

**Comment by joepavitt** [comment]
Very rough draft layout:

<img width="617" alt="Screenshot 2022-11-23 at 17 40 36" src="https://user-images.githubusercontent.com/99246719/203613487-3d897601-e4ee-4c3e-960a-4864e461d811.png">

**Comment by ZJvandeWeg** [comment]
I'm aboard with "Features" over "product"

**Comment by ZJvandeWeg** [comment]
Features to talk about: high level:
- Orchestration
- Fleet Management
- Standardised development (templates/ stacks)
- Collaboration

**Comment by joepavitt** [comment]
@ZJvandeWeg care to expand on "Orchestration" please?

**Comment by ZJvandeWeg** [comment]
@joepavitt https://en.wikipedia.org/wiki/Orchestration_(computing)

**Comment by joepavitt** [comment]
https://www.hivemq.com/hivemq/mqtt-broker/

**Comment by joepavitt** [comment]
Latest iteration in development now:

<img width="560" alt="Screenshot 2022-12-08 at 09 33 16" src="https://user-images.githubusercontent.com/99246719/206410687-52db345c-f782-42bf-88df-f77656774fbf.png">

**Comment by joepavitt** [comment]
> https://www.hivemq.com/hivemq/mqtt-broker/

In response to the request to build a diagram similar to this, have (currently) the following 3 versions:

<img width="580" alt="Screenshot 2022-12-08 at 09 33 48" src="https://user-images.githubusercontent.com/99246719/206410885-ce767e65-59f1-4a2b-a7b9-16999ebf8858.png">
<img width="535" alt="Screenshot 2022-12-08 at 09 33 45" src="https://user-images.githubusercontent.com/99246719/206410890-f6d585d9-3357-4a26-8ab1-62ec0131b5ce.png">
<img width="506" alt="Screenshot 2022-12-08 at 09 33 41" src="https://user-images.githubusercontent.com/99246719/206410893-ddaf9982-0def-409a-84af-d7599dc6bad3.png">

**Comment by ZJvandeWeg** [comment]
@joepavitt Should this issue be closed?

**Comment by joepavitt** [comment]
The first PR was in that added the page, but was using this issue to track the other pieces I was hoping to get in too, including the 1-min videos issue, which in turn has made me reflect on the 6 "Features" we show off currently, and there need for a re-work already.

**Comment by joepavitt** [comment]
Issues for additional _features_ of the Features page are open, will now close this for sake of over-tracking/documenting progress here, as we do have a deployed Features page.
