### ISSUE TITLE
Allow last blogs title to take the full line width 

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#259]
### Description

In the overview page for blog posts the last blog article doesn't get the full line width for the title:

<img width="596" alt="Screenshot 2022-11-24 at 16 31 11" src="https://user-images.githubusercontent.com/2529595/203825829-66bc4ea0-3686-488f-a53e-5ffab06861e0.png">

**Comment by joepavitt** [comment]
not sure when, but this has been improved, titles can now go 2/3rds of the screen, don't like going full width as makes readability difficult.
