### ISSUE TITLE
Responsive largest size on the blog renders poorly on wider screens

### ISSUE THREAD

**Issue by robmarcer** [flowforge/website#274]
### Current Behavior

The [blog page](https://flowforge.com/blog/) largest responsive design doesn't render well on larger screens.

### Expected Behavior

The page should stop widening with the browser window once we reach the same width as the rest of the web site.

### Steps To Reproduce

https://d.pr/v/z7SVAB

### Environment

- FlowForge version: NA
- Node.js version: NA
- npm version: NA
- Platform/OS: Mac latest
- Browser: Chrome and Safari latest

**Comment by knolleary** [comment]
Tracked this down to this change that modified the layout template but didn't update the blog index page to match

https://github.com/flowforge/website/commit/542ed44a8c1982a169541d2839404ffdae46e26e
