### ISSUE TITLE
1.2.0 release video

### ISSUE THREAD

**Issue by robmarcer** [flowforge/website#285]

**Comment by robmarcer** [comment]
Can you review the 2 main features as well as the three 'much much more' please.

https://www.youtube.com/watch?v=2WsoB5y9xMo

@ZJvandeWeg

**Comment by ZJvandeWeg** [comment]
- Shouldn't the SSO redirect you to sign in with your Google?
- I wish there was a way to share flows with the community to test persistent context
- It's Premium vs Open-Source, not Community edition or EE. The Enterprise edition exists only in code

Also; no voice over?

**Comment by robmarcer** [comment]
> * Shouldn't the SSO redirect you to sign in with your Google?

I don't know, I've recorded it as it currently works on staging, one for @knolleary?

> * It's Premium vs Open-Source, not Community edition or EE. The Enterprise edition exists only in code

Is this OK then? I've changed the third set of text. - https://d.pr/i/Wk8s8x

> Also; no voice over?

No, these videos do not have voiceovers and I've not heard discussion of changing that. We are doing voiceovers for the longer form feature specific videos.

**Comment by ZJvandeWeg** [comment]
> Is this OK then? I've changed the third set of text. - https://d.pr/i/Wk8s8x

Yes, ok.

**Comment by knolleary** [comment]
> Shouldn't the SSO redirect you to sign in with your Google?

It did... but Rob was already signed in so Google bounced back straight away. I think you'd have to log out of google first in order to capture the full process.

**Comment by robmarcer** [comment]
Not sure if I'll be able to capture the full login without showing too much private info, I'll try now...

**Comment by ZJvandeWeg** [comment]
@robmarcer It should all be in your 1Password though?

**Comment by robmarcer** [comment]
It will still show it no matter if I but it in manually or use the password manager.

This is how it looks, nothing is shown which is a security problem - https://d.pr/v/bSsYsl

I can make it show English rather than Thai but otherwise do you think this is better?

**Comment by knolleary** [comment]
@robmarcer In English would be good :) I would suggest some editing to speed through the google screens - enough to see it has redirected you there, but not spending time watching you type your details in.

**Comment by robmarcer** [comment]
Thanks, will do.

**Comment by robmarcer** [comment]
Updated video, review please. - https://www.youtube.com/watch?v=u7TjqUAub1g
