### ISSUE TITLE
Add 1-minute video demos for each "Feature"

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#292]
### Story

#254

### Description

After feedback that we do not still communicate our features clearly enough, and that we are still quite text-heavy, I propose that in order to better communicate what FlowForge offers, any "Features" we are selling as part of FlowForge should be demonstrated with a sub 1-minute video.

**Draft Design:**

<img width="1160" alt="Screenshot 2022-12-15 at 13 41 51" src="https://user-images.githubusercontent.com/99246719/207873837-271fb9ed-56ac-463e-88ba-c0278f9bfc14.png">

**Proposed Videos:**

Our current Features list is as follows:

- [ ] Node-RED at Scale
    - Demo: Deploy Node-RED in 1 Minute (ensure we have multiple Node-RED instances already in the team)
- [ ] Fleet Management & Remote Deployment
    - Demo: Update Edge Device Flows Remotely
- [ ] Advanced Collaboration
    - Demo: Team Management, Team Libraries (1.2) & Live Presence (1.3)
- [ ] Frictionless Orchestration
    - I'm really not a fan of this "Feature" - its too vague and buzzwordy
    - Demo: ??? 
- [ ] Standardised Environments
    - Demo: Project Templates & Node-RED Upgrades 
- [ ] Reduced Operational Overheads
    - Demo: Audit Logs
        - Feels weak, need more?

**Comment by joepavitt** [comment]
Missing key demo-able features given the list above are:
- SSO
- Project-to-Project Nodes
- Version Control & Snapshots
- Env vars & context (@Steve-Mcl can you expand on what the value/example of this feature is please?)

**Comment by ZJvandeWeg** [comment]
cc @robmarcer

**Comment by robmarcer** [comment]
@joepavitt I am looking at doing videos for each major video which is part of a release, feels like we should use the same format?

**Comment by Steve-Mcl** [comment]
> * Env vars & context (@Steve-Mcl can you expand on what the value/example of this feature is please?)

Hi Joe.

The Env Vars and context play nicely with and essentially extend other features (like Project Nodes)

I am uncertain of the format most helpful to you so I will put a couple of use case / scenarios below.


### Multiple device, optional components.

#### Scenario
* I have a cloud project and 10 remote devices
* Each device has core features (Type 3)
   * Temperature measurement
   * Humidity measurement
* 4 devices have additional visual status (Type 2)
   * 1 Multicoloured LED for temperature
   * 1 Multicoloured LED for humidity
* 1 device has additional rotary dials
  * 1 for temperature setting (Type 1)
  * 1 for humidity setting

#### Project 
* The node-red Project has 3 flows
   * Interface
      * This flow communicates status and control between the device and the cloud project
      * This flow runs on all devices (Types 1, 2 and 3)
   * Common
      * This flow reads and stores the device sensors values
      * This flow runs on all devices (Types 1, 2 and 3)
   * Visual Status
      * This flow updates the device LEDs
      * This flow runs only on device types 1 & 2
   * Control
      * This flow reads and stores the device rotatory dials
      * This flow runs  only on device type 1

#### Solution
* Add each device to the project and use the Device Type field to differentiate Device capabilities:
  * e.g. 5 devices get the Device Type value `TH-TYPE3`
  * e.g. 4 devices get the Device Type value `TH-TYPE2`
  * e.g. 1 device getd the Device Type value `TH-TYPE1`
* Create the 3 flows with the following properties:
   * The Visual Flow is only executed when env var `FORGE_DEVICE_TYPE` is equal to `"TH-TYPE2"`
   * The Control flow is only executed when env var `FORGE_DEVICE_TYPE` is equal to `"TH-TYPE1"`
   * When the Common flow is running on a device, it is designed to:
      * Always transmit the collected sensor values, device name and ID (using `FORGE_DEVICE_NAME` AND `FORGE_DEVICE_ID`) to a broadcast project node
      * Conditionally read LED status (via project node) when `FORGE_DEVICE_TYPE` is `"TH-TYPE2"`
      * Conditionally read and store the rotary dial value (via project node) when `FORGE_DEVICE_TYPE` is `"TH-TYPE1"`
   * When the Common flow is running on the cloud, it is designed to:
      * listen (via project node) for incoming values and store these in a database
      * provide a dashboard and override for the set values


---

So I know I said "a couple of use case / scenarios" but that took longer to write and may not be useful to you.

Please let me know if you want more (or less) or even just a chat 1:1 - there are many really good use cases for the combination of these three features.

**Comment by joepavitt** [comment]
"Deploy in 1 Minute" could in fact be the demo for "Reduced Operation Overheads", then need a better demo for Node-RED at Scale/in Production

**Comment by joepavitt** [comment]
@robmarcer given the new feature videos you put together for Release 1.3, could we do a similar format for these please? Focussing on the value for each "Feature" we list.

May still be some back and forth over what the features are, happy to have them change from the 6 we have now if more appropriate/important demos to surface.

**Comment by joepavitt** [comment]
@robmarcer noticed this still sat in 1.6 - any plans for these in 1.7? I'd be happy to take this off your hands if you'd prefer

**Comment by ZJvandeWeg** [comment]
Closing for now, as it's not the biggest priority.
