### ISSUE TITLE
blog post "upgrading flowforge" hyperlink results in a 404

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/website#301]
### Current Behavior

![chrome_SAQedEWZP4](https://user-images.githubusercontent.com/44235289/209173865-1dc66709-c1a0-4929-87a3-20763f928d05.gif)

### Expected Behavior

link should drive customer to the upgrading docs

### Steps To Reproduce

visit Release 1.2 blog: https://flowforge.com/blog/2022/12/flowforge-1-2-0-released/#upgrading-flowforge

click the upgrading link

### Environment

- FlowForge version: 1.2
- Platform/OS: Win 11
- Browser: Chrome

**Comment by Steve-Mcl** [comment]
@robmarcer

**Comment by robmarcer** [comment]
Thanks @Steve-Mcl, fixed by https://github.com/flowforge/website/pull/302/commits/191e5939c8aa657af7120205428001f03c79d2cd
