### ISSUE TITLE
Make Blog Easier to Navigate/Search

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#303]
### Description

With all the additional (and regular) great content that is now being added to our blog, it's becoming trickier to navigate and search our blog. 

Proposed Solutions/Improvements:

- **Different Tile Styles:** Part of the challenge is a visual scanning issue, in that the article tiles are all _very_ similar, we could look at different colour combinations, or auto-generated tile patterns for different types of articles (e.g. Releases, Funding Announcements, Inside FlowForge)
- **Tagging/Filtering**, Each article is given one (or multiple) category/topic, permits us to venture into wider content types (e.g. Onboarding a non-techy to GitHub) - I really like how PostHog do theirs:

<img width="1083" alt="Screenshot 2022-12-23 at 10 42 01" src="https://user-images.githubusercontent.com/99246719/209322255-6798d130-8a7a-4404-befd-ddeb085d8203.png">

inspiration: https://posthog.com/blog

**Comment by iskerrett** [comment]
I agree each blog needs to have a unique graphic that includes words that relate to the blog topic. The current homogeneous tile format doesn't add any value.

FWIW, I don't really like the posthog graphics since they don't actually convey any information about the blog topic.

**Comment by iskerrett** [comment]
I like the [gitlab blog](https://about.gitlab.com/blog/ )  and I more familiar with [HiveMQ ](https://www.hivemq.com/blog/).

Doing unique graphics for each blog post is more time consuming but they can also be reused for social media.

**Comment by joepavitt** [comment]
https://posthog.com/blog/dynamic-open-graph-images

PostHog have a really neat way of doing this for the socials. Auto-generated OpenGraph tiles for each post. A nice balance of procedural to save time, but personal/unique to each post to make it more shareable/engaging.

**Comment by iskerrett** [comment]
I agree it is a good idea to automate the creation of OpenGraph images. However, if I understand correctly the graphics are pretty static but they overlay unique text based on the page.  This is a good approach but it still creates similar tiles that are not differentiated if all put on the same page, ie the blog home page.

**Comment by joepavitt** [comment]
Think there can be some middle ground whereby we have a few tiles/themes for different categories of article, e.g. a Node-RED themed tile for those articles. 

Then, we use the relevant theme, with article preview/title for the images.

**Comment by joepavitt** [comment]
Exploring tile ideas/designs: https://www.figma.com/file/hXDN5PnY3TmeQSv3n7Hna5/FlowForge-Website?node-id=817%3A2776

Will add some layout options in the next week or two.

**Comment by joepavitt** [comment]
Thinking about the categories of content that we will publish, so far, given we already have published, we have:

- Community Newsletter
- Node-RED Tutorials
- FlowForge Tutorials
- Release Announcements
- News
- Customer Stories

**Comment by joepavitt** [comment]
proposal:

<img width="1057" alt="Screenshot 2023-06-01 at 18 26 16" src="https://github.com/flowforge/website/assets/99246719/860b51b4-2417-44c7-97ea-dff9b208d925">

**Comment by joepavitt** [comment]
Have spent 4 hours on this today, and am concluding that this is not possible with Eleventy (using Edge functions, etc.) - this should have been a few minutes of work. Until we move away from Eleventy, this will not be a feature we can add.

**Comment by joepavitt** [comment]
progress is available on https://github.com/flowforge/website/tree/blog-nav-tags

- I added the filter buttons & respective CSS classes
- Managed to get `blog.posts` added to the Eleventy Edge `globalData`
- Could access the `edge.url.search` to get the query params (if present)
- Could produce an edge-rendered for-loop for the global edge data

Blockers:
- No access to many eleventy filters tat we're reliant upon when edge rendering
- No access to the GenerateSVGPost functionality on edge either

**Comment by joepavitt** [comment]
ZJ's 💡 

- use `/blog/<filter>
- Make blog a component
- Duplicate the blog page multiple times, each endpoint available.
- Buttons then navigate to each child page

**Comment by joepavitt** [comment]
Just spent another 2 hours on this given @ZJvandeWeg's idea and still concluding that it isn't possible with Eleventy. Tried:

-  `{% include %}` - automatically passes context to the included HTML, which meant we could loop, but `async` shortcodes do not work and trip the rendering (commented on an old Eleventy issue [here](https://github.com/11ty/eleventy/issues/2244#issuecomment-1574006731))
-  `{% import %}` - Requires use of `macros` (but they don't support async), `set` (doesn't support async) or `setAsync` (see [here](https://github.com/11ty/eleventy/issues/2108)) which doesn't doesn't work at all, even with a Hello World example.

all had their individual downfalls, and again led me to wanting to leave Eleventy behind asap. Developer experience is awful and is taking up days of my time weekly.
