### ISSUE TITLE
Update the email mailing list form to post to hubspot

### ISSUE THREAD

**Issue by robmarcer** [flowforge/website#317]
### As a:

maintainer of our email marketing list

### I want to:

Update the sign up form on our website to post signups to Hubspot (new CRM) rather than Buttondown (old CRM).

### So that:

Now we have moved over to using Hubspot for emailing customers any new sign ups are posted to Hubspot and the UX for people who are signing up makes sense.

### Acceptance Criteria

- [x] Update the form (https://flowforge.com/blog/#sign-up) to write sign ups to Hubspot's API - https://legacydocs.hubspot.com/docs/methods/forms/submit_form
- [x] Update the sign up UX so that the person who has signed up gets a confirmation that their email address has been saved. I'd suggest an inline confirmation rather than taking the user to a new page.

**Comment by iskerrett** [comment]
@robmarcer can you check buttondown again. Reading the code on this page it looks like it new names were still being written to Buttondown?

**Comment by robmarcer** [comment]
Hello, yes it currently writes the signups to Buttondown but also to Hubspot as Hubspot picks up interaction with any forms on the website via there javascript add-in. As soon as the form is updated I can get rid of our Buttondown account.
