### ISSUE TITLE
Create webinar page

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#326]
### Description

I would like to create a page for our webinars that will have threemain parts:
1) top part will be promotion of the upcoming webinar and a Hubspot registration form,
2) promotion of our monthly office hours and a Hubspot registration form, 
3) an archive of previous webinars that are links to the recording on our Youtube channel.

**Comment by joepavitt** [comment]
If you have any pages from other companies you've seen that you like or ideas you have in your head for layouts, please let me know and drop them here.

**Comment by joepavitt** [comment]
> promotion of our monthly office hours and a Hubspot registration form,

seems mismatched to our Webinar? Not sure why that'd live on the "Webinar" page?

**Comment by joepavitt** [comment]
> an archive of previous webinars that are links to the recording on our Youtube channel.

As a very quick win, we can just point to a playlist on our YouTube channel once we have some content

**Comment by joepavitt** [comment]
Really like what [Tyk have on their website](https://tyk.io/webinars/), particularly with the tile design and headshots:

<img width="1232" alt="Screenshot 2023-01-19 at 19 29 52" src="https://user-images.githubusercontent.com/99246719/213541550-5a4d32a7-233e-4ca5-9dea-cbf606638bc4.png">

**Comment by iskerrett** [comment]
I agree it looks good.

**Comment by iskerrett** [comment]
Confluent has similar setup but not as graphical.  https://www.confluent.io/online-talks/?language=english

Influx mixes them in with other content pieces.  https://www.influxdata.com/_resources/

HiveMQ doesn't have a great layout, imho.  https://www.hivemq.com/developers/webinars/

Overall I like Tyk the best.

**Comment by iskerrett** [comment]
> 

We can create a seperate page for Office Hours but it actually is nice cross promotion for upcoming events.

btw, have change the office hours name to be #Ask Me Anything Session

**Comment by joepavitt** [comment]
what would be the format of the AMA sessions? Where will we host them? Will they be recorded in anyway?

**Comment by iskerrett** [comment]
> what would be the format of the AMA sessions? Where will we host them? Will they be recorded in anyway?

We will host them but they won't be recorded. We will have optional registration so people will be reminded.  We will also publish a live stream once the session is live.

**Comment by robmarcer** [comment]
As an MVP solution, I suggest we duplicate the Blog system to a new section 'webinars' then populate that with the upcoming events. We can then tweak the design to differentiate it from the blog.

Does that sound like a good way to get us started @iskerrett @joepavitt?

**Comment by joepavitt** [comment]
I was gonna have a play with a design idea today, mostly because we have no webinars at the moment, so wants to populate with something a bit more "adverty", rather than archive-driven as per the existing Blog.

**Comment by robmarcer** [comment]
Let me know if I can help please.

**Comment by joepavitt** [comment]
> promotion of our monthly office hours and a HubSpot registration form,

The more I design and play with layouts, the more I feel this needs it's own standalone page like Webinars/Blog

**Comment by joepavitt** [comment]
page layout proposal:

<img width="1761" alt="Screenshot 2023-01-24 at 12 27 46" src="https://user-images.githubusercontent.com/99246719/214291640-45e9b542-e04f-4c65-a49e-e6217a9c7bb7.png">

**Comment by iskerrett** [comment]
I agree we need two pages for webinars and blogs. For the blog proposal, you aren't registering for a blog. You sign-up for a newsletter. A bit of a detail....

For the webinar page, I think it is important we have a landing page for each webinar and on that page we have the registration form. This will allow us to link directly to this registration page. I hope this makes sense.

**Comment by iskerrett** [comment]
fwiw, this is what I mean by an individual landing page.  https://tyk.io/webinar/api-management-101-102/

**Comment by iskerrett** [comment]
> @iskerrett for the `Hubspot registration form` - what data are we going to require? Just an e-mail address?

I will create the Hubspot forms. First name, last name, email and company name.

**Comment by joepavitt** [comment]
Individual landing page design for a webinar:

<img width="1110" alt="Screenshot 2023-01-24 at 16 56 07" src="https://user-images.githubusercontent.com/99246719/214357394-3cc57c5d-4dd8-40f6-970e-b58b7069d816.png">

**Comment by iskerrett** [comment]
Looks good to me.

**Comment by joepavitt** [comment]
Development progress so far:

https://user-images.githubusercontent.com/99246719/214564410-4607c986-babb-4c74-9700-58e119a0f107.mov

Still to do:
- Mobile friendly layout
- Handle/display historical webinars
- Show placeholder when no upcoming webinars (may just show the "Most Recent" instead?)
- Handle multiple webinars planned in the future, will need some date logic to only show one at a tie, although I suspect we may want to advertise multiple? Will worry about this when I need to.
- Style HubSpot form so that it ties in with page styling

**Comment by joepavitt** [comment]
Fun things I hadn't considered, we don't want to show the regsiter section for past events, and the register form needs to be unique per event I'm guessing @iskerrett?

**Comment by iskerrett** [comment]
Right now I am hoping we will have a generic form for webinars and one for the ask me anything session.

> Development progress so far:
> 
>  Screen.Recording.2023-01-25.at.12.33.14.mov 
> Still to do:
> 
> * [x]  Navigation
> * [x]  Mobile friendly layout
> * [ ]  Handle/display historical webinars
> * [ ]  Show placeholder when no upcoming webinars (may just show the "Most Recent" instead?)
> * [ ]  Handle multiple webinars planned in the future, will need some date logic to only show one at a tie, although I suspect we may want to advertise multiple? Will worry about this when I need to.

We will have two to advertise: 1) montly webinar and 2) Ask Me Anything session.

> * [ ]  Style HubSpot form so that it ties in with page styling

I can help with this.  I noticed in the video above you are not using the HubSpot form that I created already. Is this intentional?

**Comment by joepavitt** [comment]
> Right now I am hoping we will have a generic form for webinars and one for the ask me anything session.

So if they sign up interested in one webinar, they are in fact registered to _all_ webinars?

> We will have two to advertise: 1) montly webinar and 2) Ask Me Anything session.

That wasn't in the design you approved above, that I've just spent all day building. If we need to advertise two things, I'll need to re-design and re-build the page again.

**Comment by joepavitt** [comment]
> I noticed in the video above you are not using the HubSpot form that I created already. Is this intentional? 

That is the form you requested

**Comment by iskerrett** [comment]
> > I noticed in the video above you are not using the HubSpot form that I created already. Is this intentional?
> 
> That is using the code for the form you requested [here](https://github.com/flowforge/website/issues/326#issuecomment-1401905652)

But the screen recording is using a different form, hence my confusion?

**Comment by joepavitt** [comment]
That is using the form you sent me to use

**Comment by iskerrett** [comment]
> > Right now I am hoping we will have a generic form for webinars and one for the ask me anything session.
> 
> So if they sign up interested in one webinar, they are in fact registered to _all_ webinars?
> 
> > We will have two to advertise: 1) montly webinar and 2) Ask Me Anything session.
> 
> That wasn't in the design you approved above, that I've just spent all day building. If we need to advertise two things, I'll need to re-design and re-build the page again.

Sorry I guess we miscommunicated. I have been talking about a webinar and Ask Me Anything session. Can't you just have two tiles in the upcoming section?

**Comment by joepavitt** [comment]
> Can't you just have two tiles in the upcoming section?

Tricky with how the page is using the json of webinars to render the page, but possible and will do for now.

**Comment by iskerrett** [comment]
> That is using the form you sent me to use, it is not a different form

In the screen recording the form requests a phone number?  In the form I sent, it asked for a company name.

**Comment by joepavitt** [comment]
> In the screen recording the form requests a phone number? In the form I sent, it asked for a company name.

I am using the code snippet you sent me, so I'm guessing you have either mis-configured in HubSpot, or sent me the wrong code snippet.

**Comment by iskerrett** [comment]
Ok lets try it again. Here is the code from HubSpot.

<script charset="utf-8" type="text/javascript" src="//js-eu1.hsforms.net/forms/embed/v2.js"></script>
<script>
  hbspt.forms.create({
    region: "eu1",
    portalId: "26586079",
    formId: "b4ec9aa1-8648-47b3-b908-ec8597e8735d"
  });
</script>

**Comment by joepavitt** [comment]
> Ok lets try it again. Here is the code from HubSpot.
> <script charset="utf-8" type="text/javascript" src="//js-eu1.hsforms.net/forms/embed/v2.js"></script> <script> hbspt.forms.create({ region: "eu1", portalId: "26586079", formId: "b4ec9aa1-8648-47b3-b908-ec8597e8735d" }); </script>

That's the same code snippet you sent before, and it still has the phone number in it

**Comment by joepavitt** [comment]
Looking in HubSpot...

<img width="505" alt="Screenshot 2023-01-26 at 09 01 37" src="https://user-images.githubusercontent.com/99246719/214796407-132434c8-db3d-42b0-bcef-220adc4bda05.png">

It is showing the Phone Number in the preview, and on their live form here: https://share-eu1.hsforms.com/1tOyaoYZIR7O5COyFl-hzXQftty7

**Comment by joepavitt** [comment]
You had saved the changes to include Company, but not published them. I've now published them, and they are working.
