### ISSUE TITLE
Add Noindex and Nofollow to Handbook

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#336]
### Description

The company handbook has linked to private Google docs. I believe when Google tries to index these pages, it flags these pages as having links to a broken page. I would suggest we add the noindex and nofollow tag to the handbook pages.

**Comment by joepavitt** [comment]
do you have the report from google on this please, so that I can verify?

**Comment by iskerrett** [comment]
I used a tool called aHef. I will forward you the report they sent me
via email.
