### ISSUE TITLE
Improve home page performance on mobile devices

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#349]
### Description

Google Search Console is reporting flowforge.com home page is too slow on mobile devices. Our performance score is 39/100. 

For SEO, Google prioritizes mobile friendly pages so it would be nice to address this. 

[Link to the report from Google.](https://pagespeed.web.dev/report?url=https%3A%2F%2Fflowforge.com%2F&utm_source=search_console&form_factor=mobile&hl=en)

**Comment by Pezmc** [comment]
The list of proposed changes in https://github.com/flowforge/website/issues/401, will make very similar performance improvements to the checks that Google Search Console runs (they're both using lighthouse internally).

**Comment by Pezmc** [comment]
The pagespeed index is significantly improved with the work done as part of #401.

At this point the main items remaining in lighthouse reporting are all related to third party scripts (hubspot, posthog and google tag manager).

<img width="1015" alt="Screenshot 2023-02-28 at 16 39 31" src="https://user-images.githubusercontent.com/507155/221902801-f5d0b925-92c4-444a-96d3-fdb0c8de37a5.png">

@iskerrett If you're happy with the improvements, please mark this issue complete!

**Comment by iskerrett** [comment]
Great to see the performance improvements. However from the PageInsight it still seems our core web vitals is failing for mobile. Not sure what to make of that?

![image](https://user-images.githubusercontent.com/36051834/221925265-045a0884-3f98-45a7-8f12-fe57e880c29d.png)

**Comment by Pezmc** [comment]
I believe if you scroll down slightly on that screen it'll show that it's based on an average of the last 28 days, I'd expect those numbers to shift over time!

That being said, there's currently not many other changes left that we _can_ make, other than removing third party scripts like Hubspot/PostHog.

**Comment by iskerrett** [comment]
Ok I will close the issue. We can see how this changes over the next 28 days.  Thanks for the help.
