### ISSUE TITLE
Update Node-RED page to include more detail about Node-RED

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#351]
### Description

The current https://flowforge.com/node-red/ is a bit light on content about Node-RED. If we want to start getting organic search traffic about Node-RED to flowforge.com, we need to improve this page.

**Comment by iskerrett** [comment]
Here is the revised text for this site.

https://docs.google.com/document/d/1vZ3kE72g5ACP6RTmXwjta0afgzYb6VDyGyVPOEw6VFw/edit?usp=sharing

**Comment by iskerrett** [comment]
@joepavitt , I am going to need your help creating a new layout for this page. Ideally it is a stylized FAQ page but I would still like to call it an 'Introduction to Node-RED'.

**Comment by joepavitt** [comment]
<img width="713" alt="Screenshot 2023-01-28 at 11 17 56" src="https://user-images.githubusercontent.com/99246719/215263688-a6638801-44c3-4b62-a187-4fe0f74189e3.png">

No problem to add more detail, but as priority goes, I'd question it given that only 2.5% of our visitors currently explore the "What is Node-RED?" page. 

Most of our traffic is coming from nodered.org - so they'll have that information there, or from Google, where they've either searched flowforge specifically, or some variation with node-red in their search term already.

Or is the sole purpose for these changes, increasing SEO?

**Comment by iskerrett** [comment]
The strategy is to increase the number of people with visit flowforge from an organic search for Node-RED.  This will be our pillar page for NR content.

**Comment by joepavitt** [comment]
first draft design/prototype: https://www.figma.com/proto/hXDN5PnY3TmeQSv3n7Hna5/FlowForge-Website?page-id=0%3A1&node-id=406%3A1430&viewport=2426%2C-5967%2C0.9&scaling=min-zoom&starting-point-node-id=406%3A1430&show-proto-sidebar=1

Doesn't currently have the "Node-RED Resources" in, and the screenshots in the "Low Code < >" bit will be replaced with relevant Node-RED screenshots

**Comment by joepavitt** [comment]
Updated based on feedback: https://www.figma.com/proto/hXDN5PnY3TmeQSv3n7Hna5/FlowForge-Website?page-id=0%3A1&node-id=978%3A3421&viewport=1208%2C-2024%2C0.34&scaling=min-zoom&starting-point-node-id=978%3A3421&show-proto-sidebar=1

**Comment by joepavitt** [comment]
Dev work is done, just need to get the demo video into S3, which is on @ZJvandeWeg - will also need to update the `source` of video once that's settled too.
