### ISSUE TITLE
The monthly newsletters are not showing on the blog

### ISSUE THREAD

**Issue by robmarcer** [flowforge/website#352]
### Current Behavior

Although there are documents for each monthly newsletter they are not showing on the blog.

### Expected Behavior

They should be shown

### Steps To Reproduce

View the blog on the web site, the monthly newsletters are not listed.

### Environment

- FlowForge version: NA
- Node.js version: NA
- npm version: NA
- Platform/OS: MacOS latest
- Browser: Chrome latest

**Comment by robmarcer** [comment]
My theory is that this is being caused by this being added to the header:
```
tags: newsletter
```

I'm going to test removing that locally to see if it fixes it.

**Comment by robmarcer** [comment]
Removing that tag makes the blog posts show correctly. I'm going to remove the tag from all the blog posts.

**Comment by knolleary** [comment]
It looks like the tag was added via #325 which was intended to move the newsletters to their own page.

Not clear if the intent was to remove them from the news page as well, but given we don't have a link to that new page anywhere, then we do need to do something here.

**Comment by robmarcer** [comment]
My removal of the tags will fix it for now, see the PR above.

**Comment by joepavitt** [comment]
Don't remove, just list two tags:

```
tags: ['post', 'newsletter']
```
