### ISSUE TITLE
Link to "All data is encrypted since October 2022"  results in 404 

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/website#354]
### Current Behavior

On page "[Security Statment - FlowForge](https://flowforge.com/product/security/)",  the link "All data is encrypted since October 2022"  404s

### Expected Behavior

Link to document should work

### Steps To Reproduce

- Navigate to page "Security Statment - FlowForge"
- Click the link "All data is encrypted since October 2022" 

### Environment

- FlowForge version: 1.3 / current
- Node.js version:
- npm version:
- Platform/OS:
- Browser: chrome

**Comment by joepavitt** [comment]
Well this has me stumped. The link is valid, if you navigate to it directly it 404s:

<img width="1292" alt="Screenshot 2023-02-02 at 09 51 27" src="https://user-images.githubusercontent.com/99246719/216291541-ccfb9340-49ca-4b13-b8e9-b757b3d31f61.png">

if you click the relevant article in the list of blogs (which previews the same URL), it works:

<img width="1378" alt="Screenshot 2023-02-02 at 09 50 52" src="https://user-images.githubusercontent.com/99246719/216291317-8a4d2a4c-7339-4f6a-b9ba-9834c96f3fa6.png">

**Comment by joepavitt** [comment]
ah, nope, there it is... typo in `migration`
