### ISSUE TITLE
Create social media graphic for AMA session

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#371]
### Description

Ideally we have a graphic that we can use on social media to promote the upcoming AMA session.  The graphic should include the following:
Title: Ask Me Anything about Node-RED
Date:  Februay 9 @ 17:00CET / 11:00AM ET

Meet the Experts
Nick O'Leary, co-founder Node-RED & CTO @ FlowForge
Rob Marcer, Developer Advocate @ FlowForge
Two headshot of Nick and Rob

**Comment by joepavitt** [comment]
![ama-node-red](https://user-images.githubusercontent.com/99246719/215803263-367ff602-4b5e-464a-b38c-f931b38560c3.png)
