### ISSUE TITLE
Create a page of Node-RED hardware partners

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#376]
### Description

Need a page that links to all the hardware vendors that use Node-RED.

**Comment by joepavitt** [comment]
Can I get a bit more context on this please? 

What is the page for? Who is the target audience of the page? What's the message we are trying to portray?

**Comment by iskerrett** [comment]
Goal: Demostrate that Node-RED is popular and adopted widely in the Industrial IoT industry through key hardware vendors supporting Node-RED. 

Target Audience: Manufacturing / Industrial engineers

URL should be: node-red-iiot- hardware-partners


Title: Node-RED IIoT Hardware Partner

Subtitle: Node-RED has been widely adopted by industry leading hardware vendors to be their low-code development environment for their PLC and IoT Gateways.

Grid of hardware partners.
- for each partner, their logo, underneath the logo the device name and link

Here is the current list of hardware partners, ideally listed alphabetical:

- [Advantech](https://www.advantech.com/en-eu/products/node-red-gateways/sub_fb7246cc-cc10-486f-806b-30bb50a90f28)  Node-RED Field Gateway
- [Bechhoff](https://infosys.beckhoff.com/english.php?content=../content/1033/tf6720_tc3_iot_data_agent/3260672139.html&id=)  TwinCAT
- [BLIIOT Edge Computing Gateway](https://www.bliiot.com/edge-computing-gateway-p00359p1.html)  EdgeCom BL302
- [Broadsens](https://www.broadsens.com/wireless-gateway/) GU200 & GU 200S
- [Emerson](https://www.emerson.com/documents/automation/product-datasheet-pacedge-software-computing-devices-pacsystems-en-7205588.pdf) PACEdge
- [Opto22](https://developer.opto22.com/nodered/general/)  groov RIO & EPIC
- [Particle.io](https://docs.particle.io/reference/cloud-apis/node-red/) Particle
- [Pepperl+Fuchs](https://www.pepperl-fuchs.com/usa/en/classid_199.htm?view=productdetails&prodid=93839)  AS-Interface gateway
- [Raspberry Pi](https://projects.raspberrypi.org/en/projects/getting-started-with-node-red)
- [Renesas](https://www.renesas.com/us/en/products/programmable-mixed-signal-asic-ip-products/mixed-signal-asics/communication-asics/ftclick-mikrobus-compatible-interface-module) FT Click
- [Revolution Pi](https://revolutionpi.com/revpi-connect/) RevPi Connect
- [Siemens](https://github.com/SIMATICmeetsLinux/IOT2050-NodeRed-OPCUA-Server)  S7 PLC
- [Tulip](https://support.tulip.co/docs/using-node-red-with-edge-mc)  Edge MC
