### ISSUE TITLE
Create a newsletter archive page

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#378]
### Description

Need to create a page where someone can view past newsletters.

**Comment by joepavitt** [comment]
This can be achieved as part of https://github.com/flowforge/website/issues/303

We can include a "Newsletter" or "Community" tab as part of the blog, which applies the relevant filter.

**Comment by joepavitt** [comment]
Alternatively, if we want to exclude our Community Newsletters from the "Blog" content, it would be 20 mins of work to add a new "Newsletter" option to the recently added "Resources" and link to a page of just the newsletters that is styled as per blog/webinars page
