### ISSUE TITLE
Add right side navigation to blog post

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#379]
### Description

Our blog posts hav very narrow margins. On my screen the blog takes up less than 33% of the space, the rest is white space.  This is the only page on the site like this. I would suggest we widen the margins to make it easier to read and create a more standard look.

**Comment by joepavitt** [comment]
I understand the concern here, but blog content shouldn't be too wide as it discourages engagement, e.g. https://socialtriggers.com/perfect-content-width/

That article states ideal width is between 400-600px, ours is currently 650px. 

What a lot of other engaging blogs do is fill content to the left/right, which I think is our better option, e.g:

- https://posthog.com/blog/hogmail-20
- https://tyk.io/blog/a-guide-to-navigating-opinions-and-hot-topics-in-api-management/
- https://www.confluent.io/blog/cloud-kafka-meets-cloud-flink-with-confluent-and-immerok/

**Comment by joepavitt** [comment]
For the recommended/related links, any suggestion on how we'd like to populate this? I see a few options:

- Manually for every blog article, we append a few articles we think are related
    - time consuming, but ensure relevant content
- Automatically take the last x posts created by the same Author
    - easy, but funnels just to this author, and may present unrelated content
- We start tagging content (something we should be doing for https://github.com/flowforge/website/issues/303 anyway, and utilise the tags to get the most recent articles with the associated tag)
    - More upfront work, but scales better, and ensures relevant content, without funnelling to a single author.

Thoughts @robmarcer @iskerrett?

**Comment by ZJvandeWeg** [comment]
@joepavitt What about a first iteration that does just take 3 other posts at random? Or take the 'latest updates'?

**Comment by joepavitt** [comment]
Very simple styling, but it's a start point we can improve on and add some design flair to in the future:

<img width="1165" alt="Screenshot 2023-03-23 at 11 35 15" src="https://user-images.githubusercontent.com/99246719/227191663-d17c54e6-98ab-4444-8444-775377f40675.png">
