### ISSUE TITLE
Cloud SaaS Messaging

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#38]
### Description

Now we're transitioning from a 'stealth startup' to having an open source product with a "Launching soon" SaaS offering, our website and messaging needs updating.

Visitors will want to understand what problem we're solving, and what our solution is to the problem.

Calls to actions need to include:
- Installing FlowForge (For hobbyists and on-premises)
- Invite-list for ff.cloud

**Comment by sammachin** [comment]
@zj can this be closed?
