### ISSUE TITLE
Google reportings indexing error on flowforge.com

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#385]
### Description

Google is reporting that it has failed to index our entire site correctly.  This is the report I received from Google Search Console. It seems we have a number of redirects that Google doesn't like.

https://search.google.com/search-console/index/drilldown?resource_id=sc-domain:flowforge.com&item_key=CAMYCyAC&utm_source=wnc_10031170&utm_medium=gamma&utm_campaign=wnc_10031170&utm_content=msg_100059089&hl=en

**Comment by joepavitt** [comment]
This report linked includes all non-indexed pages, if we just filter to indexed pages, we get:

![Image](https://user-images.githubusercontent.com/99246719/217283112-95855738-eb88-47ac-9f0e-f8f2600cd9f9.png)

We have just requested that our careers page does not get indexed too: https://github.com/flowforge/website/pull/395 which will mean the report is completely clean.

**Comment by joepavitt** [comment]
Ideally, we would have an indexed "Jobs" or "Careers" page, but this will require us utilising Greenhouse API and building our own Job Board.

**Comment by iskerrett** [comment]
I think what many site do is have a Careers page that then links to the Open Positions on Greenhouse.  The Careers page will talk about all the benefits and values of working at the company.

**Comment by joepavitt** [comment]
> The Careers page will talk about all the benefits and values of working at the company.

yep, sensible, for us, this is all currently on http://flowforge.com/team

**Comment by joepavitt** [comment]
If we look at other OCV companies, they seem to be using the API:

- https://fleet-device-management.breezy.hr/
- https://koor.tech/career/
- https://www.mermaidchart.com/a-place-in-the-ocean/
- https://goauthentik.io/jobs/

**Comment by joepavitt** [comment]
Think this issue can now be closed as we have no redirects present on any of the indexed pages:

<img width="1382" alt="Screenshot 2023-03-02 at 21 37 08" src="https://user-images.githubusercontent.com/99246719/222561379-6a723a99-ee3d-4437-b0f6-e31b93538d5e.png">
