### ISSUE TITLE
Include generated platform docs on website

### ISSUE THREAD

**Issue by knolleary** [flowforge/website#40]
We maintain the docs for the core platform in the main repo here: https://github.com/flowforge/flowforge/tree/main/docs

We should have a means to incorporate those docs on the website to make them easier to browse and more accessible.

 - They should be versioned against individual releases
 - By default, users should be taken to the current stable release
 - There should be the 'latest' docs taken from the `main` branch (ie, in the under-development version)

This should be largely automated. As with the handbook, a GitHub action on the main repo could trigger an action here (but only if anything under the docs dir has changed... otherwise that's a lot of wasted free Action minutes). That would update the 'latest' docs.

Another action on the main repo could, when a new tag is applied, trigger an action that pulls in that tagged version of the docs under a suitable subdir and update an index of the versions available.

The more pragmatic approach would be to make that a manual task in the first instance once the basic scaffolding of the docs pages is in place.

**Comment by ZJvandeWeg** [comment]
>>>
They should be versioned against individual releases
By default, users should be taken to the current stable release
There should be the 'latest' docs taken from the main branch (ie, in the under-development version)
>>>
I suggest we iterate on this, and first just deploy 1 version only. That gets us going faster.

Other than that, I think we should assign this task to a milestone @sammachin.

**Comment by sammachin** [comment]
Agreed, Help Docs are in the roadmap for 0.3 so I've added it to that and I'll work on it in the next week or so

**Comment by sammachin** [comment]
Added Cloud and Billing docs to GH but still need to embed docs in website

**Comment by joepavitt** [comment]
I want to include reference to the current version of the platform from which the docs have been taken. Any recommendations on how best to do this? Parsing the `flowforge/package.json`? Or is there is a `git` command I can utilise here?
