### ISSUE TITLE
March webinar page

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#442]
### Description

Publish webinar page for March webinar. The topic will be Introduction to FlowForge.

**Comment by iskerrett** [comment]
@joepavitt can I get your help creating an image for the March webinar.

Title: DevOps for Node-RED: An introduction to FlowForge
Speaker: Nick
Date: March 30 @ 17:00CET/11amET

**Comment by joepavitt** [comment]
This'll be on my list for tomorrow if that's okay? Want something similar to the white style used last time, or more something different again?

**Comment by iskerrett** [comment]
Tomorrow is fine. I am fine with similar style as the last one but maybe with the FlowForge and Node-RED logo.

**Comment by joepavitt** [comment]
@iskerrett fyi - let me know any changes you'd like

![Image](https://user-images.githubusercontent.com/99246719/221232442-76a49c98-eebf-41a4-9c85-c1fb4e2efef7.png)

**Comment by joepavitt** [comment]
cleaned the devops icon a little top-left

![Image](https://user-images.githubusercontent.com/99246719/221232892-0a2351a5-2876-4532-afdf-22b5e5e939a9.png)

**Comment by iskerrett** [comment]
Looks good. Thanks

**Comment by joepavitt** [comment]
added into codebase via #441

**Comment by iskerrett** [comment]
sorry I was doing it right now too.

**Comment by ZJvandeWeg** [comment]
@iskerrett @joepavitt Should this be closed now?
