### ISSUE TITLE
Create an image for our 'Node-RED Tips' blog posts to tie them together

### ISSUE THREAD

**Issue by robmarcer** [flowforge/website#445]
### Description

Can we create a blog image for our 'Node Red Tips' posts? Such as this one? - https://flowforge.com/blog/2023/01/3-quick-node-red-tips-1/

We would use the same image for all of them.

Thanks

**Comment by joepavitt** [comment]
@robmarcer thoughts?

![Quick Tips](https://user-images.githubusercontent.com/99246719/220931314-e1881133-cb7e-4710-b7dc-f4ed935254f3.jpg)

**Comment by robmarcer** [comment]
@joepavitt I like it, thanks!

**Comment by joepavitt** [comment]
blog has already been published, right? or is there a new one to come? I'll put it straight into the repo
