### ISSUE TITLE
Product page

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#49]
### Epic

#48

### Acceptance Criteria

- [x] Top level navigation to the page
- [x] Page includes our product, it's features, and price

**Comment by joepavitt** [comment]
@sammachin do you have any material for content of this page already put together? Or general thoughts?

**Comment by sammachin** [comment]
Only the notes from the work we did in Bristol, so where we captured the different ways that FlowForge is offered, Cloud vs Self Managed etc.

**Comment by joepavitt** [comment]
Given that we only have the Self Managed (CE) and Public (Cloud) offerings at the moment, could we put together a high level 5 bullets of key messages we want to communicate on this page please?

Bristol Meeting Notes: https://www.figma.com/file/wKVJiKza0f572njbMSaUb4/Bristol-Team-Meeting?node-id=0%3A1

Also a reminder to include any particular examples you've seen, and liked, here: https://www.figma.com/file/dR9jvt0NVXSxl7RfHZJcM2/UX-Inspirations-%26-Competitors?node-id=0%3A1

**Comment by ZJvandeWeg** [comment]
> Given that we only have the Self Managed (CE) and Public (Cloud) offerings at the moment, could we put together a high level 5 bullets of key messages we want to communicate on this page please?

The focus should only be on our own offering, maybe a link to the open source code, but our public cloud offering is what we're selling. 

Sam will correct me, but right now we offer:
* A hosted and managed Node-RED in the cloud
* Audit logging
* Role based access control
* Multi-tenency.

**Comment by sammachin** [comment]
Do we want to present the Enterprise Cloud & Self Managed options even if they're 'coming soon/contact sales' to assess demand and help to present our overall positioning? 
There's nothing that would prevent us running an enterprise cloud instance today if there was a customer even if the initial feature set was the same as the others

**Comment by sammachin** [comment]
My view is that the Product Page presents all 4 options, with different CTA's
FlowForge Cloud - Request Invite/Sign Up (as appropriate)
FlowForge Enterprise Cloud - Contact Us (email)
Self Managed CE - Link to GitHub Installer Instructions
Sef Managed EE - Contact Us (email)

**Comment by knolleary** [comment]
@sammachin that fits with what we sketched in Bristol.

It would be super helpful, with your Product hat on, to write up a one-sheet on this that Joe can pull from.

**Comment by sammachin** [comment]
Something I just spotted on zapier.com/pricing:
Even though they bill you in USD they allow you to switch and show the prices in your local currency with a disclaimer about how it will vary with exchange rate, presumably they pull in some XR data and do the conversion in the browser.
I'm undecided if this is a good thing or not in terms of UX?
![image](https://user-images.githubusercontent.com/187645/157529006-5d714207-ab77-4380-8f36-e7beebf5884c.png)

**Comment by joepavitt** [comment]
> Something I just spotted on zapier.com/pricing: Even though they bill you in USD they allow you to switch and show the prices in your local currency with a disclaimer about how it will vary with exchange rate, presumably they pull in some XR data and do the conversion in the browser. I'm undecided if this is a good thing or not in terms of UX? ![image](https://user-images.githubusercontent.com/187645/157529006-5d714207-ab77-4380-8f36-e7beebf5884c.png)

I'm not sure either to be fair. I'm swaying towards including it.

**Comment by joepavitt** [comment]
@knolleary @ZJvandeWeg @sammachin I've started to put together a feature list: 

https://docs.google.com/spreadsheets/d/1HgcnMYYglP7rT_uKPpxhHpOSVhpjOrRGXrdG0I_b1s8/edit#gid=0

worth us getting together on a call to iron that out?

**Comment by ZJvandeWeg** [comment]
Had a call yesterday, initial draft of the page:

![Screenshot 2022-03-11 at 10 44 14](https://user-images.githubusercontent.com/2529595/157842727-13601ced-6d48-47bf-9659-0175dc33a91d.png)

**Comment by joepavitt** [comment]
New Design

<img width="601" alt="Screenshot 2022-03-17 at 10 54 44" src="https://user-images.githubusercontent.com/99246719/158794434-91b20f20-eab6-48de-871f-8953b0ccec17.png">

**Comment by sammachin** [comment]
maybe a clock icon for "coming soon" ?

**Comment by sammachin** [comment]
I like it, one first impression thing, the node & line under the $10 price initial made me thing it was a slider that I should drag to change the pricing

**Comment by joepavitt** [comment]
> I like it, one first impression thing, the node & line under the $10 price initial made me thing it was a slider that I should drag to change the pricing

Great feedback - will probably get rid of the node part of that and keep the gradient

**Comment by joepavitt** [comment]
Product page hero image:

<img width="901" alt="Screenshot 2022-03-31 at 16 45 49" src="https://user-images.githubusercontent.com/99246719/161096135-4b58e947-b9db-43ba-b644-471e18f8fb27.png">
