### ISSUE TITLE
"About" Page

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#51]
### Epic

#48

### Acceptance Criteria

- [x] Layout Design
- [x] Visual Design - Hero Pictogram (#)
- [x] #53
- [x] #55
- [x] #52
- [x] #54

**Comment by ZJvandeWeg** [comment]
First iteration idea: Link the handbook about company page. While not ideal, the handbook is most up-to-date.

**Comment by joepavitt** [comment]
Do have this operational so far, if we can agree on text, I'd argue this was a much better first iteration to aim for:

https://user-images.githubusercontent.com/99246719/159886758-8eec6664-eba6-4607-b4a2-a4fccf0298e5.mov

**Comment by ZJvandeWeg** [comment]
:shipit: Agreed
