### ISSUE TITLE
Need to move March AMA webinar to be list as a past webinar.

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#511]
### Description

Right now the webinar page still lists the AMA March session as an upcoming webinar. It needs to be moved to the past webinar.

**Comment by ZJvandeWeg** [comment]
@iskerrett I think that happens automatically if you schedule the next on the website

**Comment by iskerrett** [comment]
Hmm, this is news to me. It is also not really practical since we don't normally have these scheduled that far in advanced.

**Comment by iskerrett** [comment]
OK, but our most recent AMA is not listed so something is not working correctly. Can you take a look please.

**Comment by joepavitt** [comment]
That's also intentional. Given that we do not record the sessions, there is nothing to look back on? 

Easy to put them in if preferred

**Comment by iskerrett** [comment]
We did record this AMA session, hence my desire to have it listed.  https://www.youtube.com/watch?v=P0ZfQXh-mqM&t=4s

I have obviously missed how to add the recording to make it appear as a past webinar.   Would you mind updating the handbook to include what needs to be done post webinar to have the listing available  https://flowforge.com/handbook/marketing/webinars/

**Comment by joepavitt** [comment]
Okay great, last I was told, we weren't recording AMA sessions, so I'd built the "Past Webinars" section to only include the Webinars, not AMAs.

> Would you mind updating the handbook to include what needs to be done post webinar to have the listing available

There is nothing you need to do. When I said

> Easy to put them in if preferred

I was referring to development work, just need to change the archive bit to include both Webinars and AMAs.

Then, as explained above, once an AMA or Webinar session's date has passed, it will automatically list in the "Past Webinars" list.

To add the video recording, I can't remember off top of my head (I'm on my phone atm, not back to laptop until Tuesday) but there will be an example in the other webinar we did, fairly sure it's just a one line addition to the Webinar's md file.
