### ISSUE TITLE
Hubspot reporting more visitors than GA

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#513]
### Description

Since about Feb. 28/March 1, Hubspot has been reporting very high traffic numbers to our website but Google Analytics isn't reporting this spike. I believe around this time Joe/Pez were rolling out changes to the website and Posthog. I am hoping to see if we can in the root cause of this since it would be nice to have consistent data. 

Some more background:
From Feb. 1-27 Hubspot reported 2577 visitors and GA reported 2711
From Feb. 28-March 9 Hubspot reported 3039 visitors and GA reported 1258  <<< here is the divergence
If you zoom in on Feb 28 Hubspot reported 165 and GA reported 115; on March 1 Hubspot reported 258 and GA 111  <<< the beginning of the divergence

**Comment by iskerrett** [comment]
I should have mentioned that a large majority of the increase numbers comes from Direct traffic. This makes me believe it isn't really traffic but from bots or crawlers.

**Comment by joepavitt** [comment]
Is there any more noticeable data changes/trends that could help us here? Obvious changes in types of devices? Operating system? device location? If it's a bot causing the problems, which we suspect it is, we'll see a spike in something like US geo data or Linux OS for example.
