### ISSUE TITLE
Device Management Solution page

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#519]
### Description

We would like to highlight more the device management capabilities of FlowForge. To help do this we will publish a solution page that focus on device management.

Here is the draft content for the page. It is pretty short so feedback and additions are appreciated.

https://docs.google.com/document/d/17YhQYFptPjbcJO-y-KyjOTdAXdD6ckczqZmf_Fyt3s0/edit?usp=sharing

**Comment by joepavitt** [comment]
would "Fleet Management" be a term that resonated with potential customers better? Seems to be a term I've seen more commonly in the community/industry?

**Comment by iskerrett** [comment]
> 

Nothing comes to mind.

**Comment by joepavitt** [comment]
> Nothing comes to mind.

Deploy, Manage and Scale seem a good starting point?

**Comment by joepavitt** [comment]
The content we have at the moment is only 150 words too, doesn't SEO require 300 min.?

**Comment by joepavitt** [comment]
> Here is the draft content for the page. It is pretty short so feedback and additions are appreciated.

Would be great if we can follow format of the manufacturing page as I think that reads really well..

- Title
- Subtitle (4 Key Points)
- Abstract/Leading Paragraph

- 4 x Sections, each title leading with a key point)
- Diagram/Screenshot

- FlowForge adds something, something=
- _n_ items of FlowForge features explicitly added.

I think, the 3 points we have listed in the draft at the moment are suitable for the "Flowforge features" bit in the second half, but we could come up with 4 x key points for Node-RED specifically, maybe with a little FF flavouring for the remote deploy/scaling?

**Comment by iskerrett** [comment]
> I think, the 3 points we have listed in the draft at the moment are suitable for the "Flowforge features" bit in the second half, but we could come up with 4 x key points for Node-RED specifically, maybe with a little FF flavouring for the remote deploy/scaling?

I don't see this as being the same as the manufacturing page. We don't need to motivate Node-RED for device management since we want to attract people who are already trying to do this.

**Comment by joepavitt** [comment]
> Not sure why you want to follow the structure of the manufacturing page? I think diversity would be nice.

was going to be a quicker piece of dev work, as just replace content, rather than work out new layout, etc. Happy to do something bespoke

**Comment by iskerrett** [comment]
How about you let me take a stab at doing the device page. I will just take a copy of the manufacturing page and modify it.

**Comment by joepavitt** [comment]
> How about you let me take a stab at doing the device page. I will just take a copy of the manufacturing page and modify it.

sure
