### ISSUE TITLE
Create a header image for a Securing Node-RED blog post

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#529]
### Related Issue

https://github.com/flowforge/content/issues/85

In progress: https://github.com/flowforge/website/tree/85-flowforge-content-securing-node-red

### Description

**Considerations:**
- Blog Post

**Comment by joepavitt** [comment]
@robmarcer thoughts?

![Securing Node-RED](https://user-images.githubusercontent.com/99246719/226711840-66cdc1c5-4769-410f-8e1a-6a5c0db64221.png)

**Comment by joepavitt** [comment]
may look at adding a node-red flow subtly in the b/g on the left too

**Comment by joepavitt** [comment]
variations side by side:

<img width="613" alt="Screenshot 2023-03-21 at 19 19 29" src="https://user-images.githubusercontent.com/99246719/226717930-9ff09b4e-84cc-4101-a53e-27a4263fdae5.png">

**Comment by joepavitt** [comment]
@robmarcer just a reminder these are sat awaiting review/feedback

**Comment by robmarcer** [comment]
Hello, happy with option one thank you.

**Comment by robmarcer** [comment]
Hello @joepavitt Can I get option one but just saying 'SECURING NODE-RED' please?

**Comment by joepavitt** [comment]
done, uploaded to: https://drive.google.com/drive/u/1/folders/1-339j4lkxAjwnW1UKLjRGL3mdMaB8qul
