### ISSUE TITLE
`npm run clean` not Windows compatible

### ISSUE THREAD

**Issue by knolleary** [flowforge/website#532]
The `clean` tasks recently introduced are not working on Windows.

In short, when running in a PowerShell (which could be the issue, don't know if this works as intended in a normal command prompt) it ends up creating a directory called:

```
`_site
```

with a subdirectory called:

```
js`
```

The build then fails because it expects `_site/js` to exist.

https://github.com/flowforge/website/blob/d1ba57314513d75a77cb3d690c74603b40dbab56/package.json#L10-L11

**Comment by knolleary** [comment]
@Pezmc please can you take a look at this. If you need a Windows user to verify behaviour with, please rope in @Steve-Mcl

**Comment by Pezmc** [comment]
The only change here was the addition of `!(img)` so I'm not sure where windows is getting the extra ```'s from, will need @Steve-Mcl's input to track down what's happening.

**Comment by Steve-Mcl** [comment]
The issue is the use of single quotes.

The fix is remove single quotes or prefix all commands with `cross-env `

e.g. 

```
        "clean": "cross-env npx del-cli '_site/' && cross-env npx mkdirp '_site/js'",
        "clean:dev": "cross-env npx del-cli '_site/!(img)' && cross-env npx mkdirp '_site/js'",
```
