### ISSUE TITLE
About - Two Leading Points (Content)

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#55]
Need to agree/define two leading points we want to call out on our "About" page. Current layout.design shows "OpenJS" and "Open Governance":

<img width="855" alt="Screenshot 2022-03-15 at 12 13 01" src="https://user-images.githubusercontent.com/99246719/158375400-c718c4a2-dd78-404a-9f0c-b87fb68d77a3.png">

**Comment by joepavitt** [comment]
<img width="1036" alt="Screenshot 2022-03-31 at 12 37 49" src="https://user-images.githubusercontent.com/99246719/161046464-60404c50-c720-4303-ab9e-3639189e1866.png">

@knolleary I've changed the two leading points to "Node-RED" and "Open Source". The left will discuss out NR foundations, then the right will be a summary of our own philosophies and drive in the open source community.

I removed the OpenJS image/heading entirely based on the feedback you'd given in the past (and thatI definitely agreed with)

Could I get a paragraph for each please to include with the images/headings (assuming you're okay with these headings)

**Comment by knolleary** [comment]
How's this?

> Node-RED is an industry leading low-code platform that makes it easy to build applications that integrate events, data and devices. It provides the core of what we're building at FlowForge.

> We believe strongly that Open Source lives at the heart of everything we do - both in our work to push the Node-RED project forward as well as our own FlowForge platform. We strive to be good Open Source citizens and want to empower the community to get involved.

**Comment by joepavitt** [comment]
> How's this?

Yep, much prefer that to the current iteration. Will update. Thanks

**Comment by joepavitt** [comment]
<img width="940" alt="Screenshot 2022-03-31 at 12 53 20" src="https://user-images.githubusercontent.com/99246719/161048890-9d499644-e60e-4ee8-afc4-b49e0cc4a1f0.png">

Updated. We may want to balance the text amount on each side, but it's good for now.
