### ISSUE TITLE
Create social media graphic for each solution page

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#553]
### Description

I would like to start doing social media posts about our FF solutions that link to our solution pages. Right now if I link to a solution page I get the standard page image. It would be nice to have custom images for each solution page.

**Comment by joepavitt** [comment]
What lead text (if any) would like on the tiles? Page titles (`Node-RED for Manufacturing` and `Device Management for Node-RED Deployments`) would be sensible I think?

just so we have a quick iteration, I'll likely go for something from Adobe's stock libraries, with a small bit of editing, then we can iterate/improve later

**Comment by joepavitt** [comment]
Illustrator File available in here: https://drive.google.com/drive/u/1/folders/1h1or0S_mNs6rsU98cDK2EebP1RcR-1Gl

**Comment by iskerrett** [comment]
OK thanks for the update. I am curious why you have gone with a black background? Doesn't seem consistent with our normal colours.

**Comment by joepavitt** [comment]
It's the same background colour i've used on all of our other dark background tiles. [Grey 800 from our Branding Palette](https://flowforge.com/handbook/design/branding/#colour-palette).

**Comment by Yndira-FlowForge** [comment]
Hi, here's a mockup to see how these integrate in one of our social media accounts


![Image](https://user-images.githubusercontent.com/129537638/230064500-3e9a29e8-2635-4a5f-84ad-168da47eb892.png)


And here the isolated images

![Image](https://user-images.githubusercontent.com/129537638/230064743-879b78ee-ffc8-4da9-ab28-7ac3746d3f69.jpg)

![Image](https://user-images.githubusercontent.com/129537638/230064742-e1ad5dad-e98a-411f-aa3c-9c12cc9df39b.jpg)

**Comment by iskerrett** [comment]
I like them. Can you change the device management to be 'Device Management for Node-RED'.

Thanks
Ian

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett sure! Here it is

![og-solutions-page-device-management](https://user-images.githubusercontent.com/129537638/230294667-e4c13934-8bb6-4cde-9b8b-d76ad67db04f.jpg)

**Comment by iskerrett** [comment]
Excellent. I am happy with these. Can you add them to be the images for their respective solution page.
