### ISSUE TITLE
Create a Data Integration solution page

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#554]
### Description

Create a new solution page that focuses on the Data Integration use case.

Here is a rough draft of the content. https://docs.google.com/document/d/1ErE2dsYHg5tdCDDVMpBC9PTcmASSK8No6D7KCzivkb8/edit?usp=sharing

**Comment by joepavitt** [comment]
Just checking, given you've assigned this to yourself Ian, are you planning on dev'ing/designing yourself?

**Comment by iskerrett** [comment]
@joepavitt The formatting is too complicating for me to do efficiently so I need your help. I have added all the content and I think it all fits. The section on the challenges needs formatting. I also want to have at the top a graph similar to below but nicer looking.  I will open an art request too.

![image](https://user-images.githubusercontent.com/36051834/227622115-6a52bbd9-61fe-4702-9199-cb929021dec1.png)


I have linked to the branch I created. At least I hope I have....

**Comment by joepavitt** [comment]
If you have any picture on what you'd like layout wise, please do also send that, can be in any format (Figma, Powerpoint, Pen/Paper) just so I know what you were aiming for.

**Comment by joepavitt** [comment]
yes, that's hte diagram you wanted though, right? Not the page layout?

**Comment by joepavitt** [comment]
Very quick layout draft, ignore content of diagram, but layout of sections is in place, obviously subject to feedback/improvements:

https://user-images.githubusercontent.com/99246719/230168311-7bf4aa17-bbfd-497d-ad99-895273770e60.mov

**Comment by joepavitt** [comment]
updated prototype: https://www.figma.com/proto/hXDN5PnY3TmeQSv3n7Hna5/FlowForge-Website?page-id=0%3A1&node-id=1236-6629&viewport=-20944%2C-263%2C0.48&scaling=min-zoom&starting-point-node-id=804%3A2591&show-proto-sidebar=1


https://user-images.githubusercontent.com/99246719/233120897-3706559c-a48a-4266-95cb-24ca67794498.mov

**Comment by joepavitt** [comment]
@iskerrett is there any particular CTA/message you want to have at the bottom of this page like we do on the others? Not seeing anything in the Google doc

**Comment by iskerrett** [comment]
How about something like:
'Contact us to discover how FlowForge can help use Node-RED for your Data Integration requirements.
