### ISSUE TITLE
New AMA graphic for April

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#561]
### Description

We are doing a AMA session on April 13 at the same time as usual. Can we update the existing graphic image so we can start promoting the session.

**Comment by iskerrett** [comment]
PR #564 

Just the date needs to be changed. Everything else is the same.

**Comment by joepavitt** [comment]
times changed, per discussion, uploaded to here: https://github.com/flowforge/website/pull/564#issuecomment-1488774837

**Comment by joepavitt** [comment]
![AMA - Node-RED](https://user-images.githubusercontent.com/99246719/228578567-337e089f-3875-44a0-a21f-95bca443a517.png)
