### ISSUE TITLE
Marian's headshot image

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/website#563]
### Description

**Considerations:**

- Creating a headshot picture for the website.
- Use the image (https://github.com/flowforge/website/blob/marian-team-update/src/images/team/headshot-marian-ToBeEdited.jpg) to create a headshot image.
- Format should be PNG like the others.
- Specifications should match the others.

Branch: https://github.com/flowforge/website/tree/marian-team-update

**Comment by joepavitt** [comment]
Starter task for Yndira

**Comment by Yndira-FlowForge** [comment]
Hi, here it is!! 
![headshot-marian](https://user-images.githubusercontent.com/129537638/229472157-2d89dcde-d386-40db-8352-66af3eb6c9a7.png)
