### ISSUE TITLE
Open Graph Tile Template: Handbook & Docs

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#574]
### Related Issue

#573

### Description

**Considerations:**
- Open Graph Recommended Size: 1200 x 630px
- Page title should be prominent
- Should be some differentiation between our Docs/Handbook in styling/appearance
- Possibly text/content preview into the tile too?

Blog:
- Show Author & Date?

**Inspirations:**
See #573 links

**Regular posts:**

- [x] Webinars (NR)
- [x] Webinars (FF)
- [x] Meet the experts (NR)
- [x] Meet the experts (FF)
- [x] Community news
- [x] New release
- [x] Documentation
- [x] Handbook

**Comment by Yndira-FlowForge** [comment]
@joepavitt I read the articles from #573 and have been working on this. [I have a proposal for handbook & docs](https://www.figma.com/file/hXDN5PnY3TmeQSv3n7Hna5?node-id=817:2776#460574791).

I also added a checklist for all the types of images that could be dynamic too, but before I continue working on the rest of them, wanted to check with you if the designs we have would work for dynamic images.

**Comment by joepavitt** [comment]
Thanks Yndira, just added an iteration for the docs/handbook ones, and modified colouring on Community News as that teal gradient was a little uncomfortable to look at.

I've not played around too much with what limitations we have re: tiles, so not 100% what we can get away with just yet.
