### ISSUE TITLE
April Webinar Graphic

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#587]
### Description

We require a new graphic for the April webinar.

Topic title: Connect, Integrate, Visual Industrial Production Metrics with Node-RED
Speaker: Steve McLaughlin
Date: April 27 @ 17:00CEST

Deadline: Tuesday, April 3 end of day.

**Comment by joepavitt** [comment]
@Yndira-FlowForge I should have mentioned, that settings/infinity symbol is generally a "DevOps" icon, could look at adding a variant linked more to the title of this Webinar, something around visualisation?

@iskerrett the title also doesn't quite make sense? Shouldn't it be:

"Connect, Integrate & Visualise Industrial Production Metrics with Node-RED"?

**Comment by joepavitt** [comment]
@Yndira-FlowForge we have a [Noun Project subscription](https://thenounproject.com/icons/) I can call upon if you see anything on there you'd like as a starter template, e.g. [that DevOps icon came from there](https://thenounproject.com/icon/devops-cog-wheels-4346717/)

**Comment by Yndira-FlowForge** [comment]
Thanks @joepavitt for your help.
Thinking about the context I think you're right, a dashboard iconography works best in this case. Here's the updated image.
![1200x630-Webinar-April-2023](https://user-images.githubusercontent.com/129537638/229802720-3d6ba5cd-ac0f-4d95-9aa7-37bbb3d06f46.jpg)

Now, @iskerrett do you want me to put that image directly onto your [PR/branch](https://github.com/flowforge/website/pull/589) or are you happy to do it?

**Comment by iskerrett** [comment]
Looking good.  A couple of changes:
- the title needs to change to Connect, Integrate, Visualise Industrial Production Metrics with Node-RED.  Apologies for the error in the initial copy.
- Can you please add the time 17:00 CEST/ 11:00am ET.  

Thanks
Ian

**Comment by Yndira-FlowForge** [comment]
Sure, here it is
![1200x630-Webinar-April-2023](https://user-images.githubusercontent.com/129537638/229808737-bf434227-a665-403b-ab62-4d9d6752b144.jpg)

Do you want me to put that image directly onto your https://github.com/flowforge/website/pull/589 or are you happy to do it?

**Comment by iskerrett** [comment]
Sorry but you need to include 'am' in the east coast time. I would like the format to be:
17:00 CEST / 11:00am ET  

Please don't add it to the PR. Steve still needs to confirm the content.

**Comment by joepavitt** [comment]
> Sorry but you need to include 'am' in the east coast time
Seems a bit straneg to use a 24-hr clock for the first timesoze, and then a 12-hr clock for the second timezone?

**Comment by iskerrett** [comment]
North American don't live in 24 hour clocks.

**Comment by iskerrett** [comment]
Leave the graphic as it is. I know there are more important things to worry about.

**Comment by iskerrett** [comment]
@Yndira-FlowForge can you add the graphic now to the PR.  Thanks

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett done!

**Comment by iskerrett** [comment]
HI Yndira, I need to request a slight change in the title. Can you please change it to be:
Connect, Integrate & Visualise Industrial Production Metrics with Node-RED.

**Comment by iskerrett** [comment]
sorry I forgot to tag you @Yndira-FlowForge

**Comment by Yndira-FlowForge** [comment]
Closed by [#589](https://github.com/flowforge/website/pull/589)
