### ISSUE TITLE
Book a Demo social media graphic

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#597]
### Description

We want to start promoting on social media that CTA to 'Book a Demo'. Ideally we create something fairly unique with the FlowForge brand.  When we do the social media post we will add to the text the reasons to book a demo so these are not needed in the graphic.

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett, the only text you want in the image is 'Book a Demo', right?
And, do you know the size of the file you need? Would it be the same as [these](https://github.com/flowforge/website/issues/553)?

**Comment by Yndira-FlowForge** [comment]
Hi, here's the mockup

<img width="592" alt="Screenshot 2023-04-11 at 13 15 11" src="https://user-images.githubusercontent.com/129537638/231144403-d9d81214-0a59-4980-a9f5-5c807052e7ff.png">


And here the isolated image

![1200x630-sm-book-a-demo](https://user-images.githubusercontent.com/129537638/231143874-b7541042-701e-4b8d-af80-edbf73ba03fd.png)

**Comment by iskerrett** [comment]
Looks good to me.

**Comment by joepavitt** [comment]
Minor points:
- Should we capitalize the "d" in demo? 
- May also want to add a little shadow around the button, as it does clash with the pale blue a little? Shadow would break that transition a little bit better

**Comment by Yndira-FlowForge** [comment]
Here it is with the revisions ;) 

![1200x630-sm-book-a-demo](https://user-images.githubusercontent.com/129537638/231225547-ab64e24a-f9a3-46a3-85c7-b4201133a9ad.jpg)

**Comment by joepavitt** [comment]
Think that standas out better - thanks @Yndira-FlowForge

**Comment by iskerrett** [comment]
I am not sure the graphic has been added to the page. When I add a link to a twitter feed I do not get the Book a Demo graphic. I get our standard default graphic. Can someone please check this.

**Comment by iskerrett** [comment]
fwiw, I don't think the fixed worked. I still get the old image.

**Comment by joepavitt** [comment]
@iskerrett that's because you haven't reviewed and merged the PR:

https://github.com/flowforge/website/pull/678

**Comment by iskerrett** [comment]
My apologies, just realize this.

**Comment by Yndira-FlowForge** [comment]
Thank you @joepavitt for taking care of it, and I'm sorry, I didn't understand @iskerrett meant the open graph in the first place... Will check that every time from now on.

**Comment by joepavitt** [comment]
> Thank you @joepavitt for taking care of it,

@Yndira-FlowForge no big deal at all
