### ISSUE TITLE
Pictogram for data integration

### ISSUE THREAD

**Issue by Yndira-FlowForge** [flowforge/website#604]
### Related Issue

#554

### Description

Pictogram for data integration
Title: Quick and Easy Data Integration with Node-RED

**Comment by Yndira-FlowForge** [comment]
@joepavitt I was wondering if I should close this issue? have you had a chance to check out the files? Let me know if everything is okay.

**Comment by joepavitt** [comment]
Yep - all good, will close - thanks!
