### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#61]
### Epic

#48

### Acceptance Criteria
Agree on the text belonging in:
- [x] #62
- [x] #64
- [x] #65
- [ ] https://github.com/flowforge/website/issues/50

**Comment by joepavitt** [comment]
<img width="1122" alt="Screenshot 2022-03-17 at 17 28 59" src="https://user-images.githubusercontent.com/99246719/158860694-60311d70-f24f-4b8c-b636-e6686294197f.png">

**Comment by ZJvandeWeg** [comment]
@joepavitt Don't forget https://github.com/flowforge/website/issues/50 in the list of acceptance criteria.

**Comment by joepavitt** [comment]
@ZJvandeWeg have closed this as I'm happy with our Landing page design as things stand. We link to the blog/news in the header in the top-right, although do not offer a direct preview of the latest blog post on the home page, as things stand. I'm not sure where I would want this to live on the landing page at the moment, but will have a think about it, come up with some designs and move forward from there, with #50 as a standalone item.
