### ISSUE TITLE
localhost not showing new article correctly

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#610]
### Description

I am trying to test a new article on localhost. Unfortunately it does not render correctly on the website. It does render correctly on Rob's localhost.

![image](https://user-images.githubusercontent.com/36051834/230353684-d1383701-9762-4826-925b-230eb90b7e3f.png)

**Comment by ZJvandeWeg** [comment]
@iskerrett Can you push it up as PR? That way others can check it out and debug. But this might be a local issue for you?

**Comment by iskerrett** [comment]
It appears I have managed to blow away the branch I was working on. I got into a merge conflict. I will close this issues since I need to start again on the article.

**Comment by iskerrett** [comment]
fwiw, I was able to recreate the article and the problem went away. Not really sure what changed but things are working now.
