### ISSUE TITLE
Landing - Hero Tagline

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#62]
Agree on a Hero tagline for the landing page of the website. Currently, we have:

> Enterprise-ready Node-RED for your business.

and previously had:

> Open source, low code integration and automation

see #61 for where this will sit in the page design

**Comment by joepavitt** [comment]
Some other options:

> HERO: A low-code platform for collaborative development
> HERO: A low-code platform for collaborative development, Integration and automation

> HERO: Collaborative, low-code integration and automation
> HERO: Collaborative, low-code development and integration

I agree re: sentiment of Node-RED, and the secondary hero line should emphasise the "applications", "devices", "integration" buzzwords

**Comment by ZJvandeWeg** [comment]
> But the text on the page itself was changed in https://github.com/flowforge/website/pull/43 to what is there now. As there's no discussion in that PR, I can't speak for why that change was made.

This was made as I anticipated our first users would sign up for that. As always, open to iterating.

In terms of the hero. I'd like to set us apart not against other Node-RED providers, but against No-Code/Low-Code competition. In such cases the main difference isn't collaboration, but how easy it is to connect the digital world with the physical. Yesterday I was going over the nodes library for Node-RED, and the support for PLCs and other non-consumer hardware is pretty amazing and is a true value-add.
