### ISSUE TITLE
updating .eleventy.js requires a full (and slow) server restart

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#621]
### Current Behavior

When adding a new filter of such, the debugging is slow and painful as the server requires a restart each time.

And setting up both Netlify and the images is awfully slow.

### Expected Behavior

`.eleventy.js` is hot-reloaded (if that's possible?)

**Comment by joepavitt** [comment]
This has been drastically improved by https://github.com/flowforge/website/pull/799
