### ISSUE TITLE
Landing - Hero Secondary Tagline

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#63]
Agree on text to fill the secondary tagline. Currently we have:

> Create your own workflows in our secure, scalable, collaborative environment.

and previously have had:

> Combine applications, devices and data in a secure, scalable and collaborative environment built around the open-source Node-RED project

see #61 for where this will sit in the page design

**Comment by knolleary** [comment]
See my comment in #62 - I don't think this can be discussed in isolation.

**Comment by joepavitt** [comment]
Agreed - will close this, and we can move discussion to #62
