### ISSUE TITLE
Graphic for FlowForge 1.6 release

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#631]
### Description

FlowForge 1.6 will be released this coming Thursday. We will need a graphic for the blog post. The main headline will be 'FlowForge Now Supports Multi-Instance Node-RED for Complex Application Development'

**Comment by joepavitt** [comment]
Do you want this formatted more like a standard blog tile, single header (as provided), b/g graphic/image? Rather than the format we'd used previously, e.g. https://flowforge.com/blog/2023/03/flowforge-1-5-0-released/ where we highlight top couple of features?

**Comment by joepavitt** [comment]
uploaded to: https://drive.google.com/open?id=1-MZUwdFu9SQfUKb1dRckCrvsgLFZMRQI&authuser=joepavitt%40flowforge.com&usp=drive_fs

![RELEASE 1 6 0](https://user-images.githubusercontent.com/99246719/231741100-8cbcaf83-7aec-456d-be2e-bf2580a5b9ab.png)

ended up not using the full headline proposed as it was too long for the tile, did try an iteration with _just_ that header, but it was too text heavy.
