### ISSUE TITLE
Blog Tile: import any npm module to function nodes

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#649]
### Related Issue

https://github.com/flowforge/content/issues/100

### Description

**Considerations:**
- Tile for a blog post
- Will post a low-fi idea in here shortly

**Inspirations:**
- Thinking a 3d effect with a bit of spark or something might be fun.
- Want to show off recognisable brands/integrations/logos

**Comment by joepavitt** [comment]
Think having it in 3d or pseudo3d/isometric style could really work:

<img width="620" alt="Screenshot 2023-04-14 at 10 16 43" src="https://user-images.githubusercontent.com/99246719/232003116-17a09319-c7c6-47b7-95d9-cc4fb70bd08d.png">

For the bigger "block" - worth having the Node-RED logo, but with some kind of _nod_ to the function node on it? Generic code icon maybe?

**Comment by joepavitt** [comment]
will have a think about what logos to include here and let you know

**Comment by Yndira-FlowForge** [comment]
Do you at least know how many logos there will be? I'm guessing there will be only one block for each logo, right?

**Comment by joepavitt** [comment]
Definitely one logo per block - haven't settled on exactly which logos for now, it's flexible, as a starting point, feel free to duplicate PostHog, Google, AWS a few times. Want the balance of enough that we show value, but not too many that it becomes overwhelming and difficult to consume the information

**Comment by Yndira-FlowForge** [comment]
This is what I got so far, I want to test different backgrounds, add some shadows, create the wires, but as per the 3d objects and layout, what do you think? (These are Illustrator's 3D objects)

![Image](https://user-images.githubusercontent.com/129537638/232830660-a2814a8e-df4f-4e19-9abe-eeaff7b745a2.jpg)

**Comment by joepavitt** [comment]
could also incorporate the [npm icon/logo](https://www.google.com/url?sa=i&url=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3ANpm-logo.svg&psig=AOvVaw3enzzLF73FKtuYfHxSPxRE&ust=1681919421103000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCLix457ks_4CFQAAAAAdAAAAABAE) into the smaller blocks?

**Comment by Yndira-FlowForge** [comment]
Here's with the opinionated orange hehe, as a first impression, I don't like it; but maybe from a nR user's point of view is not so bad, as you said, it would be somehow familiar... 

![Image](https://user-images.githubusercontent.com/129537638/232833405-879cf137-6a9d-4a12-ba7d-f9680c91e29e.jpg)

Maybe it would look better on a light bg?
![Image](https://user-images.githubusercontent.com/129537638/232834301-f3299d5b-9319-443b-b408-6eb40e8a4b73.jpg)

**Comment by joepavitt** [comment]
Agreed - looks odd.

Other thoughts:
- Where we have the code icon, that could get wrapped in a "node", where the node is the orange and the code con is white. Then the rest of the object is original colour?
- Prefer the dark b/g - looks like it's lit from the same source as the blocks
- Clarification required on my part from the `npm` logo, I was thinking we could have the logo on the blocks _as well_ as the brand/library logos, the npm logo could go on one of the other faces? Suspect it'll be _too much_ but would like to see it.

**Comment by Yndira-FlowForge** [comment]
I have applied all the ideas and was working on the wires, but I will resume once I know how many blocks there will be.

![npm-model-in-NR4](https://user-images.githubusercontent.com/129537638/233036390-8281ce2b-f009-496d-a380-d51145dfb5dc.jpg)

**Comment by joepavitt** [comment]
yeah, that orange doesn't work. You've got a fairly metallic material on the node-RED red too. The lighting position was also better previously as it had a better contrast on shadow. Here your lighting is behind the camera, which makes it feel quite flat.

**Comment by Yndira-FlowForge** [comment]
Here's with the previous lighting and no metallic material
![npm-model-in-NR5](https://user-images.githubusercontent.com/129537638/233042890-de027c5c-36a6-45de-8723-4594613a1e05.jpg)

I'd still like to retouch some things in photoshop, work on the background, shadows... But if you think it would better in blender, let's have that 30min session!!

**Comment by joepavitt** [comment]
Thoughts about some of the tiles we could have:

- [PostHog](https://posthog.com/)
- [Moment](https://momentjs.com/)
- [Lodash](https://lodash.com/)
- [EASY-CRC](https://www.npmjs.com/package/easy-crc) - no logo, may need to improvise with teh text-only here
- [HubSpot](https://www.hubspot.com/)

@Steve-Mcl what other ones do you see coming up in NR forums?

**Comment by joepavitt** [comment]
@Yndira-FlowForge just updated the above list with 9 libraries. Would you be able to update the graphic at your earliest convenience please?

**Comment by Yndira-FlowForge** [comment]
Here it is

![Image](https://github.com/flowforge/website/assets/129537638/2cd59716-d855-4f54-9077-c4165e9ce995)

**Comment by joepavitt** [comment]
Can we moved Easy CRC to replace the middle Google, then it looks a little more randomised, and doesn't draw attention to the repetition?

**Comment by Yndira-FlowForge** [comment]
You said "move", so, here it is

![Image](https://github.com/flowforge/website/assets/129537638/32d2d86f-9aae-4297-98e0-722832660033)

**Comment by Yndira-FlowForge** [comment]
I feel like something's missing now, like it's not balanced...

Here's another one


![Image](https://github.com/flowforge/website/assets/129537638/b2bd26ff-a5e7-4404-bd57-be1e0879138f)
