### ISSUE TITLE
OpenGraph: FlowForge Careers/Jobs

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#658]
### Description

**Considerations:**
- Open Graph Image:

Existing Format:

<img width="557" alt="Screenshot 2023-04-18 at 15 58 37" src="https://user-images.githubusercontent.com/99246719/232818030-1d3c085a-f683-4b2d-a816-b6530bce9848.png">

Want to have something similar aesthetic to the Product Roadmap tile that advertises working at FlowForge. Inciting viewers to click and find out more.

We may actually want to have a template for each job opening too, so we can share directly to a particular post. Given we still use the board directly, we need to setup a redirect on the website to point to the relevant posting explicitely.

**Comment by Yndira-FlowForge** [comment]
Hi Joe, [here's](https://drive.google.com/open?id=1ByEDUkOq4L8q9P_BfYFYISjrkkZ1muJV&authuser=yndira%40flowforge.com&usp=drive_fs) what I've got so far.

**A generic image**, may work to post more than one offer at the same time.

**An image per role**. I'm hesitating about the icon next to "We're hiring", do you think it clashes with the other pictograms? Do you like it at all??

**Comment by joepavitt** [comment]
**Image per Role:**

- Agree that the icon next to "We're Hiring" doesn't work. It's already busy enough, just the text here is fine.
- As per above, add a piece of text with "flowforge.com" would be good too.
- Otherwise, excellent.

**Comment by Yndira-FlowForge** [comment]
@joepavitt here they are, updated with your inputs, but I don't know how to set these as OGs in greenhouse ¿?


![Image](https://user-images.githubusercontent.com/129537638/236414315-ada42bff-9ec0-483e-a00c-99edc8d57bda.jpg)
![Image](https://user-images.githubusercontent.com/129537638/236414317-9f697d4d-1938-4c08-b14e-2090de48f1bf.jpg)
![Image](https://user-images.githubusercontent.com/129537638/236414316-88344b2e-e859-47b7-8c81-3862da321e05.jpg)

**Comment by joepavitt** [comment]
Thanks Yndira - we can't set in Greenhouse, need to setup a bit of redirect magic on our website. Leave it with me.
