### ISSUE TITLE
Landing - Welcome/Intro Video

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#66]
### Story

#61

### Description

On the Landing Page, we should have a short video, or quick walkthrough of the high-level features of FlowForge (and in particular FlowForge Cloud). We can iterate on this video, and make it shinier in the future, but I'm always a big fan of showing off screenshots/usability on a home page. I'm suspicious of products/companies that advertise heavily and use buzzwords everywhere, without showing anything real.

Need to define what key features we want to call out. Could storyboard this in a FigJam first, then record

**Comment by ZJvandeWeg** [comment]
First iteration of this might just be @knolleary with the recording for 0.1?

**Comment by joepavitt** [comment]
Added in 0.1 video for now - [e2c5b96](https://github.com/flowforge/website/commit/e2c5b96ea86741a3203de31d62aea990e855a3f3): <img width="1022" alt="Screenshot 2022-03-30 at 17 47 57" src="https://user-images.githubusercontent.com/99246719/160888572-14058f05-a0ed-4777-9c79-45fe2842c594.png">
