### ISSUE TITLE
Allow blog articles to be credited to people who don't show on the team page of the website

### ISSUE THREAD

**Issue by robmarcer** [flowforge/website#674]
### Description

We want to be able to use external writers for some blog posts.

To credit someone for a blog post they need to have a config file here:

https://github.com/flowforge/website/tree/main/src/_data/team

But if we add someone there they will also show here:

https://flowforge.com/team/

So we should add a way to suppress people from showing on the team page, something like:

```"employee": "false"```

**Comment by joepavitt** [comment]
Would we expect each person to require a headshot too, or want some kind of placeholder for guests?

**Comment by robmarcer** [comment]
I'd say exactly the same format (so including a photo).
