### ISSUE TITLE
May Webinar graphic

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#681]
### Description

We need a new graphic to promote the May webinar.  Here are the details"
Title: Getting Started with Node-RED Dashboard
Speaker: Rob Marcer

Abstact:  How can you use Node-RED to create dashboards and interactive graphs of your data. The answer is the Node-RED Dashboard node, the most popular node in the Node-RED community. In this webinar, Rob Marcer will take you through the steps of how to get started with the Node-RED dashboard.

Attendees of the webinar will learn the basic concepts and the steps to getting started to creating a live interactive dashboard. The webinar will feature live demonstrations and sample code that can be used by all attendees.

**Comment by Yndira-FlowForge** [comment]
Here it is

![Image](https://user-images.githubusercontent.com/129537638/234361408-af08cfb1-26b4-45ff-91f4-0f5f8230ae3b.jpg)

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett, is everything correct with this one? Do you have a PR to add it to?

**Comment by iskerrett** [comment]
It looks fine. I do not have a PR for this yet. I will work on it today.
