### ISSUE TITLE
Redesign "Pricing" (3 tears)

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#713]
### Description

Our top-level pricing display needs some thinking.

Currently - we have 22% of people clicking the "Install" option on the Pricing page:

<img width="1439" alt="Screenshot 2023-05-03 at 12 39 08" src="https://user-images.githubusercontent.com/99246719/235905799-5d952fc0-f2f3-4ca9-96ac-23b01ee8416c.png">

and only 7% click the "Join FF Cloud" option:

<img width="1450" alt="Screenshot 2023-05-03 at 12 39 31" src="https://user-images.githubusercontent.com/99246719/235905855-f40d57d7-2907-483b-96b0-cd4b7825f5c7.png">

What could we change in order to encourage more users to FF Cloud? We should be able to A/B test these results too to check for validation of improvement.

Interestingly we also get 4% of users clicking the "per Node-RED instance/month" tagline under the actual price, but this does nothing, what extra detail could we provide here?

### Epic/Story

#773

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
https://www.smashingmagazine.com/2022/07/designing-better-pricing-page/

**Comment by Yndira-FlowForge** [comment]
Hi @joepavitt I've been looking at the article you shared and some other resources... You'll find everything [here](https://www.figma.com/file/PQNHfkLutaobzGIDOIfgvH/Pricing?type=whiteboard&node-id=0%3A1&t=8YjTSDIEDvkQKTkj-1) with some notes, in case you want to check them out.

**Comment by Yndira-FlowForge** [comment]
Hi @joepavitt I'm trying to push the changes but [the test fails](https://github.com/flowforge/website/actions/runs/5048939543/jobs/9057764481#step:7:2655) and I'm not sure how to fix it... Could you please check it out?

**Comment by joepavitt** [comment]
I'm out this week, will need someone else to take a look

**Comment by Yndira-FlowForge** [comment]
Thank you so much @knolleary!! Now it works!
