### ISSUE TITLE
Blog Post Image for Release Notes 1.7

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/website#716]
### Description

**Considerations:**

- Where the image will be displayed/shared: blog post
- For next week's Release Notes, it would be great to have an image showcasing the new highlights of the 1.7 release.
- The highlights for the image are:
  - [Presenting Remote Node-RED Editor Access for Devices](https://github.com/flowforge/flowforge/issues/1821)
  - [Introducing DevOps Pipelines](https://github.com/flowforge/flowforge/issues/1492)

**Inspirations**:
/blog/2023/04/images/release-1.6.0.png

**Comment by robmarcer** [comment]
I'll need this image for Thursday morning please.

**Comment by joepavitt** [comment]
Uploaded to: https://drive.google.com/open?id=128V2unmWcDp6nVBoR7ataHjAyM4DLQ2d&authuser=joepavitt%40flowforge.com&usp=drive_fs
