### ISSUE TITLE
blog layout: Use more horizontal space

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#729]
### Description

On large or widescreen displays the view for our blog creates an ocean of whitespace both left and right of the content. It makes the content feel like it's crowded with very short line lenght for example.

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by joepavitt** [comment]
Assuming you're referring to the initial concern that was raised here (linking to my reasoning/response): https://github.com/flowforge/website/issues/379#issuecomment-1413363399
