### ISSUE TITLE
Node-RED Pillar Page

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#739]
### Description

Stats are showing poor CTR from Google search results of `/node-red`:

<img width="1361" alt="Screenshot 2023-05-11 at 08 43 37" src="https://github.com/flowforge/website/assets/99246719/d6196bbb-ca99-4ded-9751-536952bd4b70">

We are also seeing a low second page view (user going onto see an additional page after arriving) for `/node-red`:

<img width="561" alt="Screenshot 2023-05-11 at 08 52 51" src="https://github.com/flowforge/website/assets/99246719/952b6887-e353-498c-ac13-b1c1a6926fa3">

We are also scoring relatively middle-ground on "content viewed" for this page, which suggests people are scrolling the content, quickly deciding it's not for them, and leaving.

<img width="717" alt="Screenshot 2023-05-11 at 09 11 57" src="https://github.com/flowforge/website/assets/99246719/ba68e364-a898-4c25-b783-fcdfc361f1be">
<img width="725" alt="Screenshot 2023-05-11 at 09 11 38" src="https://github.com/flowforge/website/assets/99246719/eac07ef5-61d2-4a83-b992-4ff23fcca054">

As a result, we should look at revamping `/node-red` with a new style/layout in order to improve these results.

### Audience Persona

Our main persona here is someone that is not really aware of what Node-RED is and should be targeting education on Node-RED, upselling it, and consequently encouraging a sign up to FlowForge in order to give it a go. They generally arrive at this page directly from google, or from the "What is Node-RED?" link on our homepage.

The core purpose of this page is SEO though, so the content (for now) should not change too much, and should be driven by @iskerrett. I'll focus on designing an engaging layout/design, rather than the existing text-heavy approach.

All data can be viewed in this PostHog Dashboard: https://eu.posthog.com/dashboard/2926

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Also have [this issue](https://github.com/flowforge/website/issues/376) which mentions about adding Node-RED hardware partners to advertise its popularity

**Comment by joepavitt** [comment]
Further insight, as was considering removing the video, but seems as though 20% of viewers of this page watch the video:

<img width="512" alt="Screenshot 2023-05-11 at 11 00 42" src="https://github.com/flowforge/website/assets/99246719/3dfa4409-10eb-4c59-a4cf-ff11311c4166">

**Comment by Yndira-FlowForge** [comment]
Yes, I think the video is a keeper, although, it has no audio and it goes really fast for someone who doesn't know Node-RED... I think there's room for improvement there.
And the structure, I agree is text-heavy as it is, it needs some visuals to add some variety and make the reading a bit lighter.
I would suggest adding a button at the end for the free trial, something like "get started". I know there's a link at the "How can I get started using Node-RED?" but a CTA after someone goes through all that reading seems sensible.

**Comment by joepavitt** [comment]
Just to document changes in user behaviour with this change implemented:

**2nd Page Conversion:**

- Before: 31%
- After: 35%

**CTA Conversion (Join Cloud)**

- Before: 3.5%
- After: 7.0%
