### ISSUE TITLE
Create second iteration of ctrlX landing page

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#768]
### Description

We need to update https://flowforge.com/partners/ctrlx/ and make it visible on our site.

The update page should make it clear for:
- how existing ctrl X customer get support
- how ctrlX customers can benefit from using FF
- what FF provides for hosting node-red on ctrlx

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by iskerrett** [comment]
Added a layout diagram.  https://docs.google.com/drawings/d/1Fh1e8G3vo9CDjqSWJq81c1feK2mX6TlSlJJC8tJEp7g/edit?usp=sharing

**Comment by iskerrett** [comment]
I like the iterated layout, especially the top part. However, I don't think the contact support button is appropriate there. I have left detailed comments in figma. I hope this is okay. 

What I would like to suggest is use the top part of the second concept and the bottom part of the first iteration.

**Comment by joepavitt** [comment]
Can I just get some clarification please Ian. You've asked for bottom of the left iteration, and top of the right iteration, but the comment you've left suggests you want the bottom of the right too?

<img width="1588" alt="Screenshot 2023-06-08 at 08 50 57" src="https://github.com/flowforge/website/assets/99246719/7aa96fea-b0ab-4b76-bd41-20b756339509">

**Comment by Yndira-FlowForge** [comment]
Hi @joepavitt 

Ian didn't see these in the same order as we have them in Figma. For him (and in terms of iteration), the second concept is the one on the left in your screenshot.

I think he means this
<img width="718" alt="Screenshot 2023-06-08 at 10 20 40" src="https://github.com/flowforge/website/assets/129537638/77371bf4-a31f-4712-aa10-f7ee6c5df233">

I have just swapped their positions on Figma to avoid any confusion. I apologize for not doing it yesterday.

**Comment by joepavitt** [comment]
Nothing to apologise for @Yndira-FlowForge - thanks for the clarification

**Comment by iskerrett** [comment]
Yes this is what I mean :-). In the future it might be useful to name or number the iterations.

I like the revised mockup.  Are you happy with it?

One slight change, I would change the top button to be 'Get Node-RED for ctrlX'.

**Comment by iskerrett** [comment]
@MarianRaphael can you provide feedback on the revised ctrlx page?

**Comment by MarianRaphael** [comment]
I really like it. It looks fantastic, thank you for the work!

**Comment by MarianRaphael** [comment]
> @MarianRaphael @iskerrett what would be the URL for the 'Get Node-RED for ctrlX' button?

I need to verify this with Rexroth and will provide you with the information as soon as possible.

**Comment by iskerrett** [comment]
This brings up a good point that we can't actually publish this page until we are officially available in the crtlX marketplace. @MarianRaphael is it safe to say this will be still another 2-3 weeks?

**Comment by MarianRaphael** [comment]
Unfortunately, I think yes
