### ISSUE TITLE
Custom widget for flow JSON

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#772]
### Description

On our blog we often have a Flow for copying in raw JSON. Usually accompanied by a screenshot of that flow. It would be great if we have a nice UX around the combination.

Maybe the first iteration is displaying the screenshot with an obvious copy button for readers to copy the JSON to the clipboard?

/cc @joepavitt 

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by Yndira-FlowForge** [comment]
Closed by https://github.com/node-red/flow-library/pull/100
