### ISSUE TITLE
Landing - Welcome/Intro Video

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#78]
### So that: I can get an insight into what the platform offers and whether or not I would be interested in using it

Follow on from the 0.1 video currently being used as a placeholder from #66

### Acceptance Criteria

- [x] Storyboards of the video (should be about 60-90 seconds long)
- [x] Draft animation
- [x] Full quality rendered mp4 
- [ ] Added to the website landing page

**Comment by joepavitt** [comment]
First Draft/Pass, still some placeholders. Currently only 35s long (this may be enough?):


https://user-images.githubusercontent.com/99246719/172610223-54b85af5-5373-4660-b06a-69f20d3b68c8.mp4

**Comment by joepavitt** [comment]
Thinking that the border of the white screen animations needs to be more obvious, and demonstrate some more depth to it? Possible screen reflection gimmick, or something like that?

**Comment by joepavitt** [comment]
Think the pace of the "3000 Integrations Available" => "Easily Wire Components" transition feels like it decelerates too much

**Comment by joepavitt** [comment]
Rather than "Easily Wire Components", thinking I should call out (or add to the graphic) explicit "API", "Hardware", "Services", eetc.

**Comment by joepavitt** [comment]
Music Option 1:

https://user-images.githubusercontent.com/99246719/173880697-0ab5fa66-2dfa-4880-95b7-bcfb08df6ebc.mp4

**Comment by joepavitt** [comment]
Music Option 2:

https://user-images.githubusercontent.com/99246719/173884003-ab6c8ad0-61bd-4ec4-a915-869c6b8fdc07.mp4

**Comment by Steve-Mcl** [comment]
> Landing.Video_2.mp4 

I like the background music in this one - mellow yet uplifting ;)

However, the intro is quite harsh (peaking) an doesnt seem "normalised" with the rest of the track.

> Getting.Started.mp4 

Pretty much same as 👆 (intro peaking)

Otherwise, me likey.

**Comment by joepavitt** [comment]
thanks @Steve-Mcl - I'll stick with the `_2` music and level out the intro.

For the getting started and tutorial type videos, going to sticking with the track we have in "Getting Started"

**Comment by joepavitt** [comment]
Okay, unless any major objections (and a big thanks to @Steve-Mcl for assistance on the intro audio) I think we have our landing video:

https://user-images.githubusercontent.com/99246719/174047519-b2cd826d-5986-4bd5-a1cd-30f92da35080.mp4

**Comment by knolleary** [comment]
Great job. The music is the right balance of chill and dont-send-me-to-sleep.

**Comment by joepavitt** [comment]
Had decided against the last item in the todo list (adding to Website homepage) for now, but have published to our YouTube Channel: https://www.youtube.com/watch?v=BBNzFInc_2E

This does raise a question though - maybe we should be linking to our YT from the website, and actually, maybe the landing video is a good way of doing that?

**Comment by knolleary** [comment]
Aside from whether the video is on the home page or not, we should add a link to the channel in the footer alongside the other social links.

**Comment by joepavitt** [comment]
>Aside from whether the video is on the home page or not, we should add a link to the channel in the footer alongside the other social links.

issue opened: https://github.com/flowforge/website/issues/141

Can now close this issue.
