### ISSUE TITLE
June webinar graphic

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#785]
We need a new June webinar graphic.  The title of the webinar will be: 
Building Node-RED Applications that are scalable and highly available.
Marion Denne will be speaker
Date: June 29 @ 17:00CET/11amET

**Comment by iskerrett** [comment]
Pull request 784 has the complete abstract.

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett I just added the image to your PR

**Comment by Yndira-FlowForge** [comment]
![Image](https://github.com/flowforge/website/assets/129537638/60c1bc73-345c-4726-80c9-42bab137a59e)
