### ISSUE TITLE
Graphic for new article about Node-RED community survey

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#787]
### Description

I have written a new blog posts that highlight some of the trends in the Node-RED community survey. It would be nice to have a graphic for the blog post.

Blog post is in #786

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett 

How about this one?

![Image](https://github.com/flowforge/website/assets/129537638/504dfec3-442f-40c4-8473-5eb954baba6b)

**Comment by Yndira-FlowForge** [comment]
@iskerrett done!
