### ISSUE TITLE
Iterate on customers stories page

### ISSUE THREAD

**Issue by Yndira-FlowForge** [flowforge/website#813]
### Description

Now that we're introducing a new customer story, a few issues araised:

- The date is not showing in the blog page for the most recent story.
- It says "undefined" below the title of all stories except for the most recent one.
- The tile height of the small ones is being defined by the height of the image.
- The line that separates the first 3 stories from the rest is too short. Same issue with the rest of rows.
- The new story will have an artwork instead of a photo, so this will clash with the title, as the hero banner uses that image as a background inside the article. Maybe we need to take the title out of the hero banner.
- The [original design](https://github.com/orgs/flowforge/projects/10/views/1?filterQuery=customer&pane=issue&itemId=26285052#:~:text=it%20would%20be-,like%20this,-iskerrett) had a place for the logo of the company, but if the tile image is an artwork, this wouldn't work.
- Should we add a pagination as we did for the blog page?

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-FlowForge** [comment]
@iskerrett thinking about the idea of adding an artwork instead of a photo:

- It would be easier for the clients/partners to just send a photo and their logo (positive version, that best fits in a square, transparent background), than creating an artwork that fits our web.
- I've been checking out a few references and so far, I haven't found anything with artwork, just photos or logos. [HiveMQ](https://www.hivemq.com/customers/) [Mendix](https://www.mendix.com/customer-stories/) [Zapier](https://zapier.com/customer-stories)
- I think that when we have more stories, having different styles, colors, fonts, won't look as good (lack of consistency)
- I know they mean to send an artwork but, would it be possible to ask them for a photo and their logo as well?

**Comment by joepavitt** [comment]
If the customer has sent us artwork, we use artwork. I haven't seen it, but I'm sure we can make it work with the layout. We will still need a logo though.

If it truly looks awful, then we can have that conversation.

**Comment by iskerrett** [comment]
What dimensions do we need?  Even if it is a photo or artwork?

**Comment by Yndira-FlowForge** [comment]
Closed by #830
