### ISSUE TITLE
[A/B]: Move pricing under Product menu item

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#818]
### What are your variants?

control: Keep existing top navigation bar
test: Move pricing menu item to be under the product menu item.  The product menu item should be in the following order: Features, Pricing, Roadmap, Customer Stories.

### What does success look like?

Example success metrics could be:
 - Visitors view Feature page increases.

**Comment by joepavitt** [comment]
For the success metrics here, we can do two types:

1. Absolute Metric (e.g. raw number of page views)
2. Funnel Metric (% of users going from A to B)

My gut thinking is that Funnel would be represent our interests here. Funnel of Homepage > Features - we want to increase from X to Y%

Sounds sensible @iskerrett?

**Comment by iskerrett** [comment]
I am not really sure I get the difference but I am fine with either or both metrics.

**Comment by joepavitt** [comment]
Netlify had an issue with edge functions earlier today that stopped me from doing it, so have started my Dashboard work. Can try and get to this today now that Netlify have reported they're back up and running

**Comment by joepavitt** [comment]
Setting up the Experiment as follows:

### Primary Metric: % Homepage > Features

- **Existing Conversion**: 6.9%
- **Target Conversion**: 15.0%
- **Recommended Duration**: 2.9 Days

### Secondary: % Homepage > Pricing

- **Existing Conversion**: 23.4%

### Secondary: % Homepage > CTA Join

- **Existing Conversion**: 15.5%

_note:_ secondary metrics are for monitoring only, the success of the experiment is purely defined by the outcome of the "Primary Metric"

**Comment by joepavitt** [comment]
Experiment: https://eu.posthog.com/experiments/992

**Comment by joepavitt** [comment]
early results (only 1/3 of recommended sample size atm) suggest this was a very good move:

<img width="1251" alt="Screenshot 2023-06-09 at 09 35 37" src="https://github.com/flowforge/website/assets/99246719/2b463e8d-05de-4ad1-bafa-c298063a377e">

**Comment by joepavitt** [comment]
Just to drop latest results for this as we now have more visitors than the recommended sample size:

### Primary

<img width="1440" alt="Screenshot 2023-06-15 at 08 51 51" src="https://github.com/flowforge/website/assets/99246719/3edff904-29de-4422-9fba-5ba1790e4025">


### Secondary Metrics:

<img width="549" alt="Screenshot 2023-06-15 at 08 51 31" src="https://github.com/flowforge/website/assets/99246719/0df73fde-4106-4242-81d7-58eb52586494">

**Comment by joepavitt** [comment]
### Control:

<img width="1399" alt="Screenshot 2023-06-20 at 08 34 38" src="https://github.com/flowforge/website/assets/99246719/dc82ac33-9170-48a7-870f-1765e329a698">

### Nested:

<img width="1406" alt="Screenshot 2023-06-20 at 08 34 53" src="https://github.com/flowforge/website/assets/99246719/89727385-a388-4bc8-832c-166380e664b2">

Said in the last website meeting that I would investigate where the "missing 5%" was going in the nested state for this test. Interestingly, it's going to the "Sign Up", with the "Sign Up" becoming the most popular link to click on the "nested" option. We then lose a lot more of that traffic, than those going to sign up, having seen features/pricing in the "control".

In both of these situations, we end up with about 10% ending up signing up to FlowForge Cloud within 2 steps, just taking different routes:

- Control: Homepage > Pricing > Sign Up
- Nested: Homepage > Sign Up

We cans ee from the A/B Experiment though, that the "Nested" option does provide a slightly higher conversion within the whole user journey (17.6% vs. 16.3%)

I'd be really interested to see how this panned out with "Features" being a top-level item.

**Comment by joepavitt** [comment]
Also, I think I may have worked out the discrepancy between the bounce/engagement rate for GA vs. PostHog - would GA consider a move from Website > app.flowforge.com a bounce? PostHog doesn't as it shares analytics across the two, I _believe_ that GA does? Does this sound reasonable @iskerrett?

**Comment by iskerrett** [comment]
> Also, I think I may have worked out the discrepancy between the bounce/engagement rate for GA vs. PostHog - would GA consider a move from Website > app.flowforge.com a bounce? PostHog doesn't as it shares analytics across the two, I _believe_ that GA does? Does this sound reasonable @iskerrett?

I am not really sure how GA does down rates. Sorry.

**Comment by joepavitt** [comment]
@Yndira-FlowForge has this been closed off now, and stopped, or is the AB Testing code still running?

**Comment by Yndira-FlowForge** [comment]
Hi @joepavitt it's still running, stopping it is in my to-do list

**Comment by Yndira-FlowForge** [comment]
These are the latest metrics:
<img width="1342" alt="Screenshot 2023-07-08 at 15 49 58" src="https://github.com/flowforge/website/assets/129537638/34d2c0bd-5a51-41b3-a871-d2d12fda8606">

The control version is "the winner" for this round. 

I've already created a pull request to revert the changes and stop the A/B test.

**Comment by Yndira-FlowForge** [comment]
> I'd be really interested to see how this panned out with "Features" being a top-level item.

Are we going to test this option?
