### ISSUE TITLE
Iterate on title and description of nodered page

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#819]
### Description

We need to increase the click-thru rate of our node-red page. The current ctr is 1.8%. The current title is Introduction to Node-RED which doesn't really differentiate ourselves from other search results.

I would suggest changing the title to be: Node-RED Resources

Text under the title should be: A collection of technical resources that answer your questions about Node-RED.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Just to record the only iteration I'd made to this was https://github.com/flowforge/website/pull/741 not sure if we can use GA to check if that had any impact (I doubt it)

**Comment by iskerrett** [comment]
> Just to record the only iteration I'd made to this was #741 not sure if we can use GA to check if that had any impact (I doubt it)

GA picked up these changes but it didn't move the needle on CTR.
