### ISSUE TITLE
Update Product Features page content

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#824]
### Description

The current feature page is out of date and I think too high level.  I would like to create a Feature page that is a source of information for visitors who want to have a better understanding of the FlowForge capabilities.

Here is the first draft of the content. I haven't really thought about the graphical layout. A couple of things I hope we can get from a new ui:
- something easy to skim through
- room for screen shots and/or videos.  We don't have videos now but I do hope in the future we will.

https://docs.google.com/document/d/1orWf1rywyy1qJF84azoZ4cMVZtERz7p58LCs_Jbcpos/edit?usp=sharing

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by iskerrett** [comment]
@Yndira-FlowForge I am happy to chat with you about ui ideas for this page.

**Comment by Yndira-FlowForge** [comment]
I forgot to mention that even though you didn't ask for it, I felt that the page could benefit from having a call-to-action (CTA) at the end.

**Comment by iskerrett** [comment]
I really like this. Great work!

My preference would be for not so much white space between sections.

**Comment by Yndira-FlowForge** [comment]
> My preference would be for not so much white space between sections.

@iskerrett done! (the prototype has been updated with the changes)

**Comment by joepavitt** [comment]
I feel like a more condensed piece of content (highlighting titles and a one-liner) for each major feature would be beneficial, instead of the architecture diagram. It's quite a technical diagram to lead a "Features" page with, which should be approachable and informative about the value for the customer, that diagram doesn't do that imo.

As for the bottom CTAs - FF Cloud should be the middle option, with Open Source on the left.

**Comment by Yndira-FlowForge** [comment]
@joepavitt I'd like to use a video instead, like [mendix](https://www.mendix.com/) or [fastgen](https://fastgen.com/) (this is the one zj shared on [#design](https://flowforgeworkspace.slack.com/archives/C03387T7UFP/p1686153377654959)). This would also help us with the goal of decreasing the time to "wow" action in our OKRs. However, @iskerrett mentioned that we don't have anything like that just yet... 

What would you say are the major features? Or did you mean using all of the 8 titles we currently have?

> As for the bottom CTAs - FF Cloud should be the middle option, with Open Source on the left.

Done, it was like that because Ian listed them in that order, and I thought it was intentional.

**Comment by joepavitt** [comment]
> However, @iskerrett mentioned that we don't have anything like that just yet...

We have an outdated video here: https://www.youtube.com/watch?v=w8CQD4eMVa4 which was more of an advert for FlowForge. All resources for that in After Effects

**Comment by joepavitt** [comment]
> I'd like to use a video instead, like [mendix](https://www.mendix.com/) or [fastgen](https://fastgen.com/) (this is the one zj shared on [#design](https://flowforgeworkspace.slack.com/archives/C03387T7UFP/p1686153377654959)).

Those examples are both on the homepage, if we want similar, we should look at replacing Nick on ours. For the "Features" page, I think there should be a single highlight of 3-4 major features we think hit home with customers at the top (I think all 8 may be too much, but worth experimenting?). Then they get details as they scroll.

**Comment by iskerrett** [comment]
@joepavitt I disagree with you comments about a more condense page. We need a page that provides technical details about what we do. I really like the layout Yndira has done here.

**Comment by iskerrett** [comment]
> I feel like a more condensed piece of content (highlighting titles and a one-liner) for each major feature would be beneficial, instead of the architecture diagram. It's quite a technical diagram to lead a "Features" page with, which should be approachable and informative about the value for the customer, that diagram doesn't do that imo.

I disagree the diagram is perfect for this page. We want an overview of the capabilities of FlowForge in one picture.

**Comment by joepavitt** [comment]
> I disagree with you comments about a more condense page.

I'm not saying the whole page needs to be more condensed just the top part is not very valuable right now. The diagram is too technical, offers nothing about "Features" for FlowForge. The features should be front and center on a "features" page. Detailed content is important, and should remain, but highlight points should be available without scrolling.

Something like:

<img width="1041" alt="Screenshot 2023-06-14 at 12 30 33" src="https://github.com/flowforge/website/assets/99246719/c3478494-5057-4eac-8b99-1bba969975fe">

**Comment by Yndira-FlowForge** [comment]
@iskerrett we were just working on it to see how it could be improved.

I think what Joe is proposing is an improvement, putting the most important features at the top while keeping all the technical details and reducing the scrolling length...

**Comment by iskerrett** [comment]
I think we are over thinking this page. I am fine with your last iteration and I would encourage everyone to move forward so we can move on to other things.

**Comment by iskerrett** [comment]
@MarianRaphael
