### ISSUE TITLE
Header image for a blog post 'Exploring High Availability for Node-RED in FlowForge'.

### ISSUE THREAD

**Issue by robmarcer** [flowforge/website#838]
### Related Issue

https://github.com/flowforge/content/issues/121

### Description

**Considerations:**
Blog post

**Inspirations:**

We could use this same artwork?  - https://flowforge.com/blog/2023/05/bringing-high-availability-to-node-red/

**Comment by robmarcer** [comment]
This was planned to be published next week but due to a change or schedule it's going out today, Therefore I will need the artwork by 3pm if that's possible.

**Comment by Yndira-FlowForge** [comment]
Hi @robmarcer here it is
![Exploring-High-Availability-for-Node-RED-in-FlowForge](https://github.com/flowforge/website/assets/129537638/e5b94f39-0d1b-4c58-befa-ff8877dc6214)
