### ISSUE TITLE
Improve docs landing page

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#842]
### Description

**As a:** new or existing user of FlowForge,

**I want to:** quickly find answers on how to get the most out of the platform

**So that:**  I can effectively use FlowForge.

------------

### Acceptance Criteria

- [ ] Separate documentation structure based on use-cases
    - [ ] Current docs are focussed on user vs admin, not use-case
- [x] Improve structure so the left menu bar is use-case based
- [x] Link to community forum from the landing page
- [x] More prominent search box
- [ ] Getting started guide for each use-case

### Proposed structure

1. FlowForge user how to
   1. Team management
   2. Application, how to build one
   3. Migration from Node-RED to FF NR
   4. Instance settings
   5. Security features
   6. .. etc for each feature
1. Device Agent (Edge compute agent)
   1. How to install
   2. How to use
   3. Point to point data transfer
   4. Upgrade agent
   5. Roll out security updates
1. Self-Managed FlowForge
   1. Marketplaces
   2. Local / Docker / K8S
   3. SSO
1. FF Cloud
   1. Billing
   2. Stacks
   4. Templates
   5. Network
   6. SSO
1. how to get support
   1. Community

Examples:
1. https://docs.gitlab.com/
2. https://stripe.com/docs
3. https://docs.netlify.com/

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Looking into the Algolia analyttics, seems our most common search terms are:

- device
- sso
- email
- mqtt
- git
- agent
- export

**Comment by joepavitt** [comment]
really trying to work out how to have a first iteration at this, and struggling to bitesize it. Going to need to be shifting around a fair few files.

**Comment by MarianRaphael** [comment]
First Iteration see: https://github.com/flowforge/flowforge/pull/2646
