### ISSUE TITLE
Broken video in handbook marketing page

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#854]
### Description

It appears there are broken video links in the marketing page on videos. 

https://flowforge.com/handbook/marketing/videos/#assets

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by iskerrett** [comment]
Also broken link on this page: https://flowforge.com/handbook/development/frontend/services/

**Comment by Yndira-FlowForge** [comment]
Hi @ZJvandeWeg, I was talking with Joe about this and he mentioned that you could upload them to our Amazon S3 server instead, they're all in /src/handbook/videos
