### ISSUE TITLE
Cookie preferences button doesn't work

### ISSUE THREAD

**Issue by knolleary** [flowforge/website#896]
### Current Behavior

The link to manage cookie preferences doesn't work in the page footer:

<img width="398" alt="image" src="https://github.com/flowforge/website/assets/51083/11e8549a-2850-4f06-8b36-06769c56702b">

### Environment

- Date:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by MarcusRichardson** [comment]
I also have this
