### ISSUE TITLE
Provide logo's of FF users on the website

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#897]
### Description

There's little social proof on the website, that needs improving. I want at least 5 logos on the website of FlowForge users.

1. Heatweb
2. Enexis
3. Airship
4. Iniationware
5. Bosch

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-FlowForge** [comment]
Hi @ZJvandeWeg which logos can I use?

**Comment by Yndira-FlowForge** [comment]
Hi @ZJvandeWeg is something like this what you had in mind?.
I added them right btf. They're all in gray to avoid color clashes and to provide a visual cue that they are related.
![Homepage](https://github.com/flowforge/website/assets/129537638/6f0a04ee-c81c-400c-9de7-10a36f018781)

**Comment by ZJvandeWeg** [comment]
That's a good first iteration indeed!
