### ISSUE TITLE
Product page feedback

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#91]
### Current Behavior

1. Ticks are sometimes red. Which can be associated with 'bad'. While the feature is there and works
2. There's no legend explaining what the tick means, but more importantly the clock.
3. Consider splitting the page into "product" and "pricing"

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by ZJvandeWeg** [comment]
cc @joepavitt would appreciate your input here.

**Comment by joepavitt** [comment]
Thanks ZJ. There should be hover behaviour on the different icons explaining what each of the icons refer to, but it appears that isn't working.

RE; the colour/red, whilst I acknowledge the connotation of red to negativity (although, the opposite in Asia), it is our primary colour scheme.

RE: Splitting - I agree.

**Comment by joepavitt** [comment]
@ZJvandeWeg @sammachin what content do we want to be focussing on with the "product" page, if we're pulling "Pricing" out as standalone?

**Comment by sammachin** [comment]
At this stage I'm not sure we have enough to split the product and pricing into separate pages, there's still only one price point and 2 'flavours' of the product. 

I do think the price should be more prominent. at the moment you have to scroll quite a way down the product page, to see it. 
I think the problem we need to solve is "Our pricing isn't obvious" but I don't think a separate page is the right way to fix that at the moment,

Having just looked at the page again I can see we have "from $15 a month"  in the hero text but I totally missed that the first couple of times,

I do feel that the Key Features icons on the product page are taking quite a lot of space quite high up, the tables should be more front and centre.

**Comment by joepavitt** [comment]
We could follow the [tyk approach](https://tyk.io/price-comparison/), which has a "Platform" and "Pricing" split. Feel like tat suits us more. Focus on FlowForge, it's features and what it offers on the "Platform", then the "Pricing" does what is says on the tin.

**Comment by sammachin** [comment]
so in effect our existing table on product becomes the pricing page and there's a new platform page which goes into more detail about the features?
That could work

**Comment by joepavitt** [comment]
Worth noting that design updates are being shared to #99 which addresses some of the points ZJ has raised.

**Comment by joepavitt** [comment]
With the features/pricing extracted to "Pricing", and our "Product" page being changed to "Platform" - what content do we want to major on this page?

- Key Features (as per existing Product page?

and what else?

**Comment by joepavitt** [comment]
New Pricing page has been merged in #107. This issue will now focus it's attention on a re-worked "Platform" page as per discussion above.
