### ISSUE TITLE
Blog header image for an article explaining how to write data to InfluxDB from Node-RED

### ISSUE THREAD

**Issue by robmarcer** [flowforge/website#938]
### Description

**Considerations:**
This will be used on the blog.

I'd suggest something which indicated data moving from Node-RED to InfluxDB.

The InfluxDB logo can be download from here - https://influxdata.github.io/branding/logo/brands/

**Comment by robmarcer** [comment]
Possibly something similar to this - https://flowforge.com/blog/2023/06/connect-to-hivemq-in-flowforge/

**Comment by Yndira-FlowForge** [comment]
Hi @robmarcer

![Image](https://github.com/flowforge/website/assets/129537638/cb35e688-0655-4baf-8553-40c21b742131)

**Comment by robmarcer** [comment]
Perfect, thanks!
