### ISSUE TITLE
July webinar graphic

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#950]
### Description

We will need a new graphic for our July webinar.

Title: How to deploy Node-RED out to hundreds of PLCs and IoT edge devices
Spearker: Rob Marcer
Date: July 27, 2023 @ 17:00CET / 11amET / 8amPT

**Comment by iskerrett** [comment]
Can you please add the graphic to PR #951

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett sure, I'll add it to the PR

![1200x630-Webinar-July-2023](https://github.com/flowforge/website/assets/129537638/442f0b0c-e3ef-48f0-8c06-80cb808c923d)
