### ISSUE TITLE
Release Post: v1.10.0

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#961]
### Description

An article to detail the features, updates and fixes provided in the 1.10.0 Release of FlowForge.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by iskerrett** [comment]
PR #1011

**Comment by hardillb** [comment]
AWS Marketplace entry submitted, it is currently in a manual review phase as it's our first submission.

I suggest we publish the release notes saying it will be available and we will publish a second post when it goes live.
