### ISSUE TITLE
Article arrequest

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#978]
### Description

We have a new article getting ready to be published that will require a graphic.  Pr #977

Title: Creating a Historical Data Dashboard with InfluxDB and Node-RED

The graphic can be some what similar to the graphic created for https://flowforge.com/blog/2023/07/connect-node-red-to-influxdb/

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett would this image make sense?

![Image](https://github.com/flowforge/website/assets/129537638/cf7560aa-2904-4c19-83d7-d6c4ec5dcd9d)

Or the Node-RED app should be in FFcloud?

**Comment by iskerrett** [comment]
Yes, thanks

**Comment by Yndira-FlowForge** [comment]
> Yes, thanks

Do you mean "yes, it makes sense as it is", or "yes, it should be inside a cloud with FF logo as it is [here](https://flowforge.com/blog/2023/07/connect-node-red-to-influxdb/)"?

**Comment by iskerrett** [comment]
> > Yes, thanks
> 
> Do you mean "yes, it makes sense as it is", or "yes, it should be inside a cloud with FF logo as it is [here](https://flowforge.com/blog/2023/07/connect-node-red-to-influxdb/)"?

Sorry I respond to the first question 'would this image make sense?'.  Yes it does make sense.  We don't need the FF Cloud logo here.
