### ISSUE TITLE
Create custom art work for OPC-UA article part 2

### ISSUE THREAD

**Issue by Hisma** [flowforge/website#982]
### Related Issue

https://github.com/flowforge/website/pull/981

### Description

**Considerations:**
- blog post.  You can use same image theme as opc article part 1 but use the title specifically for this article & add "part 2" at the bottom.

**Comment by Hisma** [comment]
@Yndira-FlowForge would like to target publishing the article tomorrow, so please have request done by tomorrow.

**Comment by Yndira-FlowForge** [comment]
Hi @Hisma here it is
![How-to-Deploy-a-Basic-OPC-UA-Server-in-Node-RED2](https://github.com/flowforge/website/assets/129537638/5bd5aaaf-2bca-42eb-ab1e-24082a1dac3b)

**Comment by Hisma** [comment]
Can you please change the text to match the name of the article?
"How to Build a Secure OPC-UA Server for PLCs in Node-RED"

**Comment by Yndira-FlowForge** [comment]
Hi @Hisma sorry, here it is

![2-How-to-Build-a-Secure-OPC-UA-Server-for-PLCs-in-Node-RED](https://github.com/flowforge/website/assets/129537638/7aa7c181-286a-42af-a9cc-ae8ed8dd21a4)

**Comment by Hisma** [comment]
Got it!

**Comment by Yndira-FlowForge** [comment]
![2-How-to-Build-a-Secure-OPC-UA-Server-for-PLCs-in-Node-RED](https://github.com/flowforge/website/assets/129537638/64759504-4b14-4ef4-b11f-cd4d9ed4324e)

**Comment by Yndira-FlowForge** [comment]
Here's updated the image for part 1
![1-How-to-Deploy-a-Basic-OPC-UA-Server-in-Node-RED](https://github.com/flowforge/website/assets/129537638/dd0132b6-8e0e-4f07-92dd-a76221f15a2a)
