### ISSUE TITLE
List community edition on the product page

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#99]
### Description

Previously it was decided to only list the commercial editions on our product page. Have received 2 questions so far why the open source variant isn't listed. As such, I feel it should be added.

**Comment by joepavitt** [comment]
New table WIP design with 3 columns (and CE included):

<img width="988" alt="Screenshot 2022-05-05 at 10 13 56" src="https://user-images.githubusercontent.com/99246719/166894563-8a1344a3-2937-4344-9268-60059b70de95.png">

Need to add flourish around the table itself, and I haven't completely settled in icons/colours, but all feedback welcome

**Comment by sammachin** [comment]
We don't yet have a firm decision on some of the coming soon features being CE/EE so I'm a little nervous about saying something like Shared Team Library being coming soon to CE if we then decide to make that an EE feature?

**Comment by sammachin** [comment]
I still think we should be going for the original 4 flavours presentation here, either with the switch between hosted/self managed or all 4 on one table.

**Comment by joepavitt** [comment]
> We don't yet have a firm decision on some of the coming soon features being CE/EE so I'm a little nervous about saying something like Shared Team Library being coming soon to CE if we then decide to make that an EE feature?

Would you like the relevant rows removed entirely? Or variation of messaging/style?

**Comment by knolleary** [comment]
I would leave the rows in, just remove the icon for the CE column. Nothing stops us adding it back on a case-by-case basis as we firm up plans.

Couple other suggested tweaks:

 - What are our thoughts on renaming 'Coming soon' to 'On the roadmap' ? "Soon" is doing a lot of heavy lifting in terms of how quickly some of those features can be delivered.
 - Remove the 'Additional Cost' icon from the footer if it isn't actually used.
 - Rename SSO to `Single Sign On (SSO)`

**Comment by sammachin** [comment]
Yup better to under promise on coming soon features for CE in my opinion.

**Comment by joepavitt** [comment]
@knolleary have made all of those changed.

@sammachin - which "on the roadmap" features can I leave in CE, and which should I leave out for now?

**Comment by sammachin** [comment]
I would take out all the "on the roadmap" icons from CE, it also helps to renforce the value in the paid offerings this way

**Comment by sammachin** [comment]
`Available on Apache 2.0` doesn't quite sound right? how about `Open Source Licensed` or `Apache 2.0 Licensed`

**Comment by joepavitt** [comment]
With new updates. @sammachin I've kept the 3 columns for now, as I know how much friction the tabbed system caused last time, I also like the unification of Enterprise into a single column for now too. As the offerings evolve and are more differentiated, then I'd be pro- switching back to 2 tabbed system.

<img width="879" alt="Screenshot 2022-05-05 at 12 07 05" src="https://user-images.githubusercontent.com/99246719/166911174-860a4145-247e-4aa6-9289-16806e15845a.png">

**Comment by sammachin** [comment]
OK, can we change the title of `Cloud Enterprise` to just `Enterprise` though, the first really sounds a bit too fluffy!

**Comment by joepavitt** [comment]
> OK, can we change the title of `Cloud Enterprise` to just `Enterprise` though, the first really sounds a bit too fluffy!

Any objection if I also change `FlowForge Cloud` to just `Cloud`?

**Comment by sammachin** [comment]
Feels a little short just `Cloud`
We could have:
Community Edition
Cloud Edition
Enterprise Edition 

?

**Comment by ZJvandeWeg** [comment]
Love the second iteration @joepavitt. Great job. Agree with @sammachin and having "X edition". That works.

Good job everyone!

**Comment by sammachin** [comment]
That then gives us a statement of "FlowForge is one product, available in 3 editions" which is quite a neat way to describe it in a conversation, certainly better than "flavours" I've been using until now 😂

**Comment by joepavitt** [comment]
Alternative option: 

<img width="1738" alt="Screenshot 2022-05-05 at 12 46 42" src="https://user-images.githubusercontent.com/99246719/166916810-d2070369-7bd3-42e7-837d-9fa63c37f752.png">

**Comment by ZJvandeWeg** [comment]
I do like it, very clear on the pricing and like how it brings out the rest of design of the page better.

**Comment by joepavitt** [comment]
> I do like it, very clear on the pricing and like how it brings out the rest of design of the page better.

It feels more "finished" to me

**Comment by sammachin** [comment]
One small tweak the CTA buttons on each of the editions, is there a 3rd color we can use? I get the red for the cloud signup now, and making the community one a softer blue but is there something stronger we can use for enterprise?

**Comment by sammachin** [comment]
I guess its the 2+1 thing that looks odd to me, I get having the focus on your primary CTA but when there's only 2 other options it feels odd them bing the same, what about having CE on a white button (maybe with the GH logo) and Enterprise on Teal?

**Comment by joepavitt** [comment]
> I guess its the 2+1 thing that looks odd to me, I get having the focus on your primary CTA but when there's only 2 other options it feels odd them bing the same, what about having CE on a white button (maybe with the GH logo) and Enterprise on Teal?

Not a fan of asymmetry
